package com.zkzy.portal.base.admin.api.entity;

import java.io.Serializable;
import java.util.List;

public class EvaluationTables implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_TABLES.ID
     *
     * @mbggenerated Thu Jun 15 17:55:19 GMT+08:00 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_TABLES.TABLENAME
     *
     * @mbggenerated Thu Jun 15 17:55:19 GMT+08:00 2017
     */
    private String tablename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_TABLES.TABLEDESC
     *
     * @mbggenerated Thu Jun 15 17:55:19 GMT+08:00 2017
     */
    private String tabledesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_TABLES.SYNCHRONOUS
     *
     * @mbggenerated Thu Jun 15 17:55:19 GMT+08:00 2017
     */
    private Short synchronous;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_TABLES.CREATETIME
     *
     * @mbggenerated Thu Jun 15 17:55:19 GMT+08:00 2017
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_TABLES.MODIFYTIME
     *
     * @mbggenerated Thu Jun 15 17:55:19 GMT+08:00 2017
     */
    private String modifytime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_TABLES.ID
     *
     * @return the value of EVALUATION_TABLES.ID
     *
     * @mbggenerated Thu Jun 15 17:55:19 GMT+08:00 2017
     */

    private List<SystemTableProperty> tablePropertys;

    public List<SystemTableProperty> getTablePropertys() {
        return tablePropertys;
    }

    public void setTablePropertys(List<SystemTableProperty> tablePropertys) {
        this.tablePropertys = tablePropertys;
    }

    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_TABLES.ID
     *
     * @param id the value for EVALUATION_TABLES.ID
     *
     * @mbggenerated Thu Jun 15 17:55:19 GMT+08:00 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_TABLES.TABLENAME
     *
     * @return the value of EVALUATION_TABLES.TABLENAME
     *
     * @mbggenerated Thu Jun 15 17:55:19 GMT+08:00 2017
     */
    public String getTablename() {
        return tablename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_TABLES.TABLENAME
     *
     * @param tablename the value for EVALUATION_TABLES.TABLENAME
     *
     * @mbggenerated Thu Jun 15 17:55:19 GMT+08:00 2017
     */
    public void setTablename(String tablename) {
        this.tablename = tablename == null ? null : tablename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_TABLES.TABLEDESC
     *
     * @return the value of EVALUATION_TABLES.TABLEDESC
     *
     * @mbggenerated Thu Jun 15 17:55:19 GMT+08:00 2017
     */
    public String getTabledesc() {
        return tabledesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_TABLES.TABLEDESC
     *
     * @param tabledesc the value for EVALUATION_TABLES.TABLEDESC
     *
     * @mbggenerated Thu Jun 15 17:55:19 GMT+08:00 2017
     */
    public void setTabledesc(String tabledesc) {
        this.tabledesc = tabledesc == null ? null : tabledesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_TABLES.SYNCHRONOUS
     *
     * @return the value of EVALUATION_TABLES.SYNCHRONOUS
     *
     * @mbggenerated Thu Jun 15 17:55:19 GMT+08:00 2017
     */
    public Short getSynchronous() {
        return synchronous;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_TABLES.SYNCHRONOUS
     *
     * @param synchronous the value for EVALUATION_TABLES.SYNCHRONOUS
     *
     * @mbggenerated Thu Jun 15 17:55:19 GMT+08:00 2017
     */
    public void setSynchronous(Short synchronous) {
        this.synchronous = synchronous;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_TABLES.CREATETIME
     *
     * @return the value of EVALUATION_TABLES.CREATETIME
     *
     * @mbggenerated Thu Jun 15 17:55:19 GMT+08:00 2017
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_TABLES.CREATETIME
     *
     * @param createtime the value for EVALUATION_TABLES.CREATETIME
     *
     * @mbggenerated Thu Jun 15 17:55:19 GMT+08:00 2017
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_TABLES.MODIFYTIME
     *
     * @return the value of EVALUATION_TABLES.MODIFYTIME
     *
     * @mbggenerated Thu Jun 15 17:55:19 GMT+08:00 2017
     */
    public String getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_TABLES.MODIFYTIME
     *
     * @param modifytime the value for EVALUATION_TABLES.MODIFYTIME
     *
     * @mbggenerated Thu Jun 15 17:55:19 GMT+08:00 2017
     */
    public void setModifytime(String modifytime) {
        this.modifytime = modifytime;
    }

    @Override
    public String toString() {
        return super.toString();
    }
}