package com.zkzy.portal.base.admin.api.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class SmsBookB implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_BOOK_B.ID
     *
     * @mbggenerated Thu Jul 27 16:40:10 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_BOOK_B.NAME
     *
     * @mbggenerated Thu Jul 27 16:40:10 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_BOOK_B.DESCRIPTION
     *
     * @mbggenerated Thu Jul 27 16:40:10 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_BOOK_B.CREATETIME
     *
     * @mbggenerated Thu Jul 27 16:40:10 CST 2017
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_BOOK_B.PID
     *
     * @mbggenerated Thu Jul 27 16:40:10 CST 2017
     */
    private String pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_BOOK_B.SORT
     *
     * @mbggenerated Thu Jul 27 16:40:10 CST 2017
     */
    private BigDecimal sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_BOOK_B.ID
     *
     * @return the value of SMS_BOOK_B.ID
     *
     * @mbggenerated Thu Jul 27 16:40:10 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_BOOK_B.ID
     *
     * @param id the value for SMS_BOOK_B.ID
     *
     * @mbggenerated Thu Jul 27 16:40:10 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_BOOK_B.NAME
     *
     * @return the value of SMS_BOOK_B.NAME
     *
     * @mbggenerated Thu Jul 27 16:40:10 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_BOOK_B.NAME
     *
     * @param name the value for SMS_BOOK_B.NAME
     *
     * @mbggenerated Thu Jul 27 16:40:10 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_BOOK_B.DESCRIPTION
     *
     * @return the value of SMS_BOOK_B.DESCRIPTION
     *
     * @mbggenerated Thu Jul 27 16:40:10 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_BOOK_B.DESCRIPTION
     *
     * @param description the value for SMS_BOOK_B.DESCRIPTION
     *
     * @mbggenerated Thu Jul 27 16:40:10 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_BOOK_B.CREATETIME
     *
     * @return the value of SMS_BOOK_B.CREATETIME
     *
     * @mbggenerated Thu Jul 27 16:40:10 CST 2017
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_BOOK_B.CREATETIME
     *
     * @param createtime the value for SMS_BOOK_B.CREATETIME
     *
     * @mbggenerated Thu Jul 27 16:40:10 CST 2017
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_BOOK_B.PID
     *
     * @return the value of SMS_BOOK_B.PID
     *
     * @mbggenerated Thu Jul 27 16:40:10 CST 2017
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_BOOK_B.PID
     *
     * @param pid the value for SMS_BOOK_B.PID
     *
     * @mbggenerated Thu Jul 27 16:40:10 CST 2017
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_BOOK_B.SORT
     *
     * @return the value of SMS_BOOK_B.SORT
     *
     * @mbggenerated Thu Jul 27 16:40:10 CST 2017
     */
    public BigDecimal getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_BOOK_B.SORT
     *
     * @param sort the value for SMS_BOOK_B.SORT
     *
     * @mbggenerated Thu Jul 27 16:40:10 CST 2017
     */
    public void setSort(BigDecimal sort) {
        this.sort = sort;
    }
}