package com.zkzy.portal.base.admin.api.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class SmsManB implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_MAN_B.ID
     *
     * @mbggenerated Thu Jul 27 16:40:22 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_MAN_B.NAME
     *
     * @mbggenerated Thu Jul 27 16:40:22 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_MAN_B.BOOKID
     *
     * @mbggenerated Thu Jul 27 16:40:22 CST 2017
     */
    private String bookid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_MAN_B.BOOKNAME
     *
     * @mbggenerated Thu Jul 27 16:40:22 CST 2017
     */
    private String bookname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_MAN_B.TELEPHONE
     *
     * @mbggenerated Thu Jul 27 16:40:22 CST 2017
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_MAN_B.SORT
     *
     * @mbggenerated Thu Jul 27 16:40:22 CST 2017
     */
    private BigDecimal sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_MAN_B.REMARK
     *
     * @mbggenerated Thu Jul 27 16:40:22 CST 2017
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_MAN_B.ID
     *
     * @return the value of SMS_MAN_B.ID
     *
     * @mbggenerated Thu Jul 27 16:40:22 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_MAN_B.ID
     *
     * @param id the value for SMS_MAN_B.ID
     *
     * @mbggenerated Thu Jul 27 16:40:22 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_MAN_B.NAME
     *
     * @return the value of SMS_MAN_B.NAME
     *
     * @mbggenerated Thu Jul 27 16:40:22 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_MAN_B.NAME
     *
     * @param name the value for SMS_MAN_B.NAME
     *
     * @mbggenerated Thu Jul 27 16:40:22 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_MAN_B.BOOKID
     *
     * @return the value of SMS_MAN_B.BOOKID
     *
     * @mbggenerated Thu Jul 27 16:40:22 CST 2017
     */
    public String getBookid() {
        return bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_MAN_B.BOOKID
     *
     * @param bookid the value for SMS_MAN_B.BOOKID
     *
     * @mbggenerated Thu Jul 27 16:40:22 CST 2017
     */
    public void setBookid(String bookid) {
        this.bookid = bookid == null ? null : bookid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_MAN_B.BOOKNAME
     *
     * @return the value of SMS_MAN_B.BOOKNAME
     *
     * @mbggenerated Thu Jul 27 16:40:22 CST 2017
     */
    public String getBookname() {
        return bookname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_MAN_B.BOOKNAME
     *
     * @param bookname the value for SMS_MAN_B.BOOKNAME
     *
     * @mbggenerated Thu Jul 27 16:40:22 CST 2017
     */
    public void setBookname(String bookname) {
        this.bookname = bookname == null ? null : bookname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_MAN_B.TELEPHONE
     *
     * @return the value of SMS_MAN_B.TELEPHONE
     *
     * @mbggenerated Thu Jul 27 16:40:22 CST 2017
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_MAN_B.TELEPHONE
     *
     * @param telephone the value for SMS_MAN_B.TELEPHONE
     *
     * @mbggenerated Thu Jul 27 16:40:22 CST 2017
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_MAN_B.SORT
     *
     * @return the value of SMS_MAN_B.SORT
     *
     * @mbggenerated Thu Jul 27 16:40:22 CST 2017
     */
    public BigDecimal getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_MAN_B.SORT
     *
     * @param sort the value for SMS_MAN_B.SORT
     *
     * @mbggenerated Thu Jul 27 16:40:22 CST 2017
     */
    public void setSort(BigDecimal sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_MAN_B.REMARK
     *
     * @return the value of SMS_MAN_B.REMARK
     *
     * @mbggenerated Thu Jul 27 16:40:22 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_MAN_B.REMARK
     *
     * @param remark the value for SMS_MAN_B.REMARK
     *
     * @mbggenerated Thu Jul 27 16:40:22 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}