package com.zkzy.portal.base.admin.api.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class SmsRecordB implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_RECORD_B.ID
     *
     * @mbggenerated Thu Jul 27 16:39:42 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_RECORD_B.FROMMAN
     *
     * @mbggenerated Thu Jul 27 16:39:42 CST 2017
     */
    private String fromman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_RECORD_B.SENDTIME
     *
     * @mbggenerated Thu Jul 27 16:39:42 CST 2017
     */
    private String sendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_RECORD_B.CONTENT
     *
     * @mbggenerated Thu Jul 27 16:39:42 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_RECORD_B.TOMANS
     *
     * @mbggenerated Thu Jul 27 16:39:42 CST 2017
     */
    private String tomans;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_RECORD_B.SUCCESS
     *
     * @mbggenerated Thu Jul 27 16:39:42 CST 2017
     */
    private BigDecimal success;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_RECORD_B.FAILURE
     *
     * @mbggenerated Thu Jul 27 16:39:42 CST 2017
     */
    private BigDecimal failure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_RECORD_B.SUBTIME
     *
     * @mbggenerated Thu Jul 27 16:39:42 CST 2017
     */
    private String subtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_RECORD_B.TOTELS
     *
     * @mbggenerated Thu Jul 27 16:39:42 CST 2017
     */
    private String totels;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_RECORD_B.STATE
     *
     * @mbggenerated Thu Jul 27 16:39:42 CST 2017
     */
    private BigDecimal state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_RECORD_B.ISTIMED
     *
     * @mbggenerated Thu Jul 27 16:39:42 CST 2017
     */
    private BigDecimal istimed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_RECORD_B.DEFTIME
     *
     * @mbggenerated Thu Jul 27 16:39:42 CST 2017
     */
    private String deftime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_RECORD_B.TYPE
     *
     * @mbggenerated Thu Jul 27 16:39:42 CST 2017
     */
    private BigDecimal type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_RECORD_B.ID
     *
     * @return the value of SMS_RECORD_B.ID
     *
     * @mbggenerated Thu Jul 27 16:39:42 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_RECORD_B.ID
     *
     * @param id the value for SMS_RECORD_B.ID
     *
     * @mbggenerated Thu Jul 27 16:39:42 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_RECORD_B.FROMMAN
     *
     * @return the value of SMS_RECORD_B.FROMMAN
     *
     * @mbggenerated Thu Jul 27 16:39:42 CST 2017
     */
    public String getFromman() {
        return fromman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_RECORD_B.FROMMAN
     *
     * @param fromman the value for SMS_RECORD_B.FROMMAN
     *
     * @mbggenerated Thu Jul 27 16:39:42 CST 2017
     */
    public void setFromman(String fromman) {
        this.fromman = fromman == null ? null : fromman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_RECORD_B.SENDTIME
     *
     * @return the value of SMS_RECORD_B.SENDTIME
     *
     * @mbggenerated Thu Jul 27 16:39:42 CST 2017
     */
    public String getSendtime() {
        return sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_RECORD_B.SENDTIME
     *
     * @param sendtime the value for SMS_RECORD_B.SENDTIME
     *
     * @mbggenerated Thu Jul 27 16:39:42 CST 2017
     */
    public void setSendtime(String sendtime) {
        this.sendtime = sendtime == null ? null : sendtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_RECORD_B.CONTENT
     *
     * @return the value of SMS_RECORD_B.CONTENT
     *
     * @mbggenerated Thu Jul 27 16:39:42 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_RECORD_B.CONTENT
     *
     * @param content the value for SMS_RECORD_B.CONTENT
     *
     * @mbggenerated Thu Jul 27 16:39:42 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_RECORD_B.TOMANS
     *
     * @return the value of SMS_RECORD_B.TOMANS
     *
     * @mbggenerated Thu Jul 27 16:39:42 CST 2017
     */
    public String getTomans() {
        return tomans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_RECORD_B.TOMANS
     *
     * @param tomans the value for SMS_RECORD_B.TOMANS
     *
     * @mbggenerated Thu Jul 27 16:39:42 CST 2017
     */
    public void setTomans(String tomans) {
        this.tomans = tomans == null ? null : tomans.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_RECORD_B.SUCCESS
     *
     * @return the value of SMS_RECORD_B.SUCCESS
     *
     * @mbggenerated Thu Jul 27 16:39:42 CST 2017
     */
    public BigDecimal getSuccess() {
        return success;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_RECORD_B.SUCCESS
     *
     * @param success the value for SMS_RECORD_B.SUCCESS
     *
     * @mbggenerated Thu Jul 27 16:39:42 CST 2017
     */
    public void setSuccess(BigDecimal success) {
        this.success = success;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_RECORD_B.FAILURE
     *
     * @return the value of SMS_RECORD_B.FAILURE
     *
     * @mbggenerated Thu Jul 27 16:39:42 CST 2017
     */
    public BigDecimal getFailure() {
        return failure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_RECORD_B.FAILURE
     *
     * @param failure the value for SMS_RECORD_B.FAILURE
     *
     * @mbggenerated Thu Jul 27 16:39:42 CST 2017
     */
    public void setFailure(BigDecimal failure) {
        this.failure = failure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_RECORD_B.SUBTIME
     *
     * @return the value of SMS_RECORD_B.SUBTIME
     *
     * @mbggenerated Thu Jul 27 16:39:42 CST 2017
     */
    public String getSubtime() {
        return subtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_RECORD_B.SUBTIME
     *
     * @param subtime the value for SMS_RECORD_B.SUBTIME
     *
     * @mbggenerated Thu Jul 27 16:39:42 CST 2017
     */
    public void setSubtime(String subtime) {
        this.subtime = subtime == null ? null : subtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_RECORD_B.TOTELS
     *
     * @return the value of SMS_RECORD_B.TOTELS
     *
     * @mbggenerated Thu Jul 27 16:39:42 CST 2017
     */
    public String getTotels() {
        return totels;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_RECORD_B.TOTELS
     *
     * @param totels the value for SMS_RECORD_B.TOTELS
     *
     * @mbggenerated Thu Jul 27 16:39:42 CST 2017
     */
    public void setTotels(String totels) {
        this.totels = totels == null ? null : totels.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_RECORD_B.STATE
     *
     * @return the value of SMS_RECORD_B.STATE
     *
     * @mbggenerated Thu Jul 27 16:39:42 CST 2017
     */
    public BigDecimal getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_RECORD_B.STATE
     *
     * @param state the value for SMS_RECORD_B.STATE
     *
     * @mbggenerated Thu Jul 27 16:39:42 CST 2017
     */
    public void setState(BigDecimal state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_RECORD_B.ISTIMED
     *
     * @return the value of SMS_RECORD_B.ISTIMED
     *
     * @mbggenerated Thu Jul 27 16:39:42 CST 2017
     */
    public BigDecimal getIstimed() {
        return istimed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_RECORD_B.ISTIMED
     *
     * @param istimed the value for SMS_RECORD_B.ISTIMED
     *
     * @mbggenerated Thu Jul 27 16:39:42 CST 2017
     */
    public void setIstimed(BigDecimal istimed) {
        this.istimed = istimed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_RECORD_B.DEFTIME
     *
     * @return the value of SMS_RECORD_B.DEFTIME
     *
     * @mbggenerated Thu Jul 27 16:39:42 CST 2017
     */
    public String getDeftime() {
        return deftime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_RECORD_B.DEFTIME
     *
     * @param deftime the value for SMS_RECORD_B.DEFTIME
     *
     * @mbggenerated Thu Jul 27 16:39:42 CST 2017
     */
    public void setDeftime(String deftime) {
        this.deftime = deftime == null ? null : deftime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_RECORD_B.TYPE
     *
     * @return the value of SMS_RECORD_B.TYPE
     *
     * @mbggenerated Thu Jul 27 16:39:42 CST 2017
     */
    public BigDecimal getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_RECORD_B.TYPE
     *
     * @param type the value for SMS_RECORD_B.TYPE
     *
     * @mbggenerated Thu Jul 27 16:39:42 CST 2017
     */
    public void setType(BigDecimal type) {
        this.type = type;
    }
}