package com.zkzy.portal.base.admin.api.entity;

import java.io.Serializable;

public class SmsWarnB implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_WARN_B.ID
     *
     * @mbggenerated Tue Aug 01 10:43:57 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_WARN_B.JOBCODE
     *
     * @mbggenerated Tue Aug 01 10:43:57 CST 2017
     */
    private String jobcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_WARN_B.JOBNAME
     *
     * @mbggenerated Tue Aug 01 10:43:57 CST 2017
     */
    private String jobname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_WARN_B.GROUPID
     *
     * @mbggenerated Tue Aug 01 10:43:57 CST 2017
     */
    private String groupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_WARN_B.GROUPNAME
     *
     * @mbggenerated Tue Aug 01 10:43:57 CST 2017
     */
    private String groupname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_WARN_B.TOMANS
     *
     * @mbggenerated Tue Aug 01 10:43:57 CST 2017
     */
    private String tomans;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_WARN_B.TOTELS
     *
     * @mbggenerated Tue Aug 01 10:43:57 CST 2017
     */
    private String totels;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SMS_WARN_B.DESCRIPTION
     *
     * @mbggenerated Tue Aug 01 10:43:57 CST 2017
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_WARN_B.ID
     *
     * @return the value of SMS_WARN_B.ID
     *
     * @mbggenerated Tue Aug 01 10:43:57 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_WARN_B.ID
     *
     * @param id the value for SMS_WARN_B.ID
     *
     * @mbggenerated Tue Aug 01 10:43:57 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_WARN_B.JOBCODE
     *
     * @return the value of SMS_WARN_B.JOBCODE
     *
     * @mbggenerated Tue Aug 01 10:43:57 CST 2017
     */
    public String getJobcode() {
        return jobcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_WARN_B.JOBCODE
     *
     * @param jobcode the value for SMS_WARN_B.JOBCODE
     *
     * @mbggenerated Tue Aug 01 10:43:57 CST 2017
     */
    public void setJobcode(String jobcode) {
        this.jobcode = jobcode == null ? null : jobcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_WARN_B.JOBNAME
     *
     * @return the value of SMS_WARN_B.JOBNAME
     *
     * @mbggenerated Tue Aug 01 10:43:57 CST 2017
     */
    public String getJobname() {
        return jobname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_WARN_B.JOBNAME
     *
     * @param jobname the value for SMS_WARN_B.JOBNAME
     *
     * @mbggenerated Tue Aug 01 10:43:57 CST 2017
     */
    public void setJobname(String jobname) {
        this.jobname = jobname == null ? null : jobname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_WARN_B.GROUPID
     *
     * @return the value of SMS_WARN_B.GROUPID
     *
     * @mbggenerated Tue Aug 01 10:43:57 CST 2017
     */
    public String getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_WARN_B.GROUPID
     *
     * @param groupid the value for SMS_WARN_B.GROUPID
     *
     * @mbggenerated Tue Aug 01 10:43:57 CST 2017
     */
    public void setGroupid(String groupid) {
        this.groupid = groupid == null ? null : groupid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_WARN_B.GROUPNAME
     *
     * @return the value of SMS_WARN_B.GROUPNAME
     *
     * @mbggenerated Tue Aug 01 10:43:57 CST 2017
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_WARN_B.GROUPNAME
     *
     * @param groupname the value for SMS_WARN_B.GROUPNAME
     *
     * @mbggenerated Tue Aug 01 10:43:57 CST 2017
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname == null ? null : groupname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_WARN_B.TOMANS
     *
     * @return the value of SMS_WARN_B.TOMANS
     *
     * @mbggenerated Tue Aug 01 10:43:57 CST 2017
     */
    public String getTomans() {
        return tomans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_WARN_B.TOMANS
     *
     * @param tomans the value for SMS_WARN_B.TOMANS
     *
     * @mbggenerated Tue Aug 01 10:43:57 CST 2017
     */
    public void setTomans(String tomans) {
        this.tomans = tomans == null ? null : tomans.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_WARN_B.TOTELS
     *
     * @return the value of SMS_WARN_B.TOTELS
     *
     * @mbggenerated Tue Aug 01 10:43:57 CST 2017
     */
    public String getTotels() {
        return totels;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_WARN_B.TOTELS
     *
     * @param totels the value for SMS_WARN_B.TOTELS
     *
     * @mbggenerated Tue Aug 01 10:43:57 CST 2017
     */
    public void setTotels(String totels) {
        this.totels = totels == null ? null : totels.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SMS_WARN_B.DESCRIPTION
     *
     * @return the value of SMS_WARN_B.DESCRIPTION
     *
     * @mbggenerated Tue Aug 01 10:43:57 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SMS_WARN_B.DESCRIPTION
     *
     * @param description the value for SMS_WARN_B.DESCRIPTION
     *
     * @mbggenerated Tue Aug 01 10:43:57 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}