package com.zkzy.portal.base.admin.api.entity;

import java.io.Serializable;

public class SystemTableProperty implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_TABLE_PROPERTY.ID
     *
     * @mbggenerated Fri Jun 16 17:19:27 GMT+08:00 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_TABLE_PROPERTY.FIELDNAME
     *
     * @mbggenerated Fri Jun 16 17:19:27 GMT+08:00 2017
     */
    private String fieldname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_TABLE_PROPERTY.FIELDESC
     *
     * @mbggenerated Fri Jun 16 17:19:27 GMT+08:00 2017
     */
    private String fieldesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_TABLE_PROPERTY.DATATYPE
     *
     * @mbggenerated Fri Jun 16 17:19:27 GMT+08:00 2017
     */
    private String datatype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_TABLE_PROPERTY.DATALENGTH
     *
     * @mbggenerated Fri Jun 16 17:19:27 GMT+08:00 2017
     */
    private int datalength = 0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_TABLE_PROPERTY.ISNULL
     *
     * @mbggenerated Fri Jun 16 17:19:27 GMT+08:00 2017
     */
    private String isnull = "Y";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_TABLE_PROPERTY.DEFAULTVALUE
     *
     * @mbggenerated Fri Jun 16 17:19:27 GMT+08:00 2017
     */
    private String defaultvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_TABLE_PROPERTY.PKEY
     *
     * @mbggenerated Fri Jun 16 17:19:27 GMT+08:00 2017
     */
    private int pkey = 0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_TABLE_PROPERTY.POINTLENGTH
     *
     * @mbggenerated Fri Jun 16 17:19:27 GMT+08:00 2017
     */
    private int pointlength = 0;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_TABLE_PROPERTY.ID
     *
     * @return the value of SYSTEM_TABLE_PROPERTY.ID
     * @mbggenerated Fri Jun 16 17:19:27 GMT+08:00 2017
     */

    private String tablename;


    private String tableid;

    private String oldfieldname;
    private String oldatatype;
    private int oldatalength;
    private String oldisnull;
    private String oldefaultvalue;
    private int oldpkey;
    private int oldpointlength;

    private int toShow;


    private int dataScale;

    private int disabled;

    public int getToShow() {
        return toShow;
    }

    public void setToShow(int toShow) {
        this.toShow = toShow;
    }

    public void setDataScale(int dataScale) {
        this.dataScale = dataScale;
    }

    public int getDataScale() {
        return dataScale;
    }

    public void setDisabled(int disabled) {
        this.disabled = disabled;
    }

    public int getDisabled() {
        return disabled;
    }

    public void setOldpkey(int oldpkey) {
        this.oldpkey = oldpkey;
    }

    public void setOldpointlength(int oldpointlength) {
        this.oldpointlength = oldpointlength;
    }

    public String getOldefaultvalue() {
        return oldefaultvalue;
    }

    public void setOldefaultvalue(String oldefaultvalue) {
        this.oldefaultvalue = oldefaultvalue;
    }

    public int getOldpkey() {
        return oldpkey;
    }

    public int getOldpointlength() {
        return oldpointlength;
    }

    public int getOldatalength() {
        return oldatalength;
    }

    public void setOldatalength(int oldatalength) {
        this.oldatalength = oldatalength;
    }

    public String getOldisnull() {
        return oldisnull;
    }

    public void setOldisnull(String oldisnull) {
        this.oldisnull = oldisnull;
    }

    public String getOldfieldname() {
        return oldfieldname;
    }

    public void setOldfieldname(String oldfieldname) {
        this.oldfieldname = oldfieldname;
    }

    public String getOldatatype() {
        return oldatatype;
    }

    public void setOldatatype(String oldatatype) {
        this.oldatatype = oldatatype;
    }

    public String getTableid() {
        return tableid;
    }

    public void setTableid(String tableid) {
        this.tableid = tableid;
    }

    private int columnid;

    public int getColumnid() {
        return columnid;
    }

    public void setColumnid(int columnid) {
        this.columnid = columnid;
    }

    public String getTablename() {
        return tablename;
    }

    public void setTablename(String tablename) {
        this.tablename = tablename;
    }

    public String getId() {
        return id;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_TABLE_PROPERTY.ID
     *
     * @param id the value for SYSTEM_TABLE_PROPERTY.ID
     * @mbggenerated Fri Jun 16 17:19:27 GMT+08:00 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_TABLE_PROPERTY.FIELDNAME
     *
     * @return the value of SYSTEM_TABLE_PROPERTY.FIELDNAME
     * @mbggenerated Fri Jun 16 17:19:27 GMT+08:00 2017
     */
    public String getFieldname() {
        return fieldname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_TABLE_PROPERTY.FIELDNAME
     *
     * @param fieldname the value for SYSTEM_TABLE_PROPERTY.FIELDNAME
     * @mbggenerated Fri Jun 16 17:19:27 GMT+08:00 2017
     */
    public void setFieldname(String fieldname) {
        this.fieldname = fieldname == null ? null : fieldname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_TABLE_PROPERTY.FIELDESC
     *
     * @return the value of SYSTEM_TABLE_PROPERTY.FIELDESC
     * @mbggenerated Fri Jun 16 17:19:27 GMT+08:00 2017
     */
    public String getFieldesc() {
        return fieldesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_TABLE_PROPERTY.FIELDESC
     *
     * @param fieldesc the value for SYSTEM_TABLE_PROPERTY.FIELDESC
     * @mbggenerated Fri Jun 16 17:19:27 GMT+08:00 2017
     */
    public void setFieldesc(String fieldesc) {
        this.fieldesc = fieldesc == null ? null : fieldesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_TABLE_PROPERTY.DATATYPE
     *
     * @return the value of SYSTEM_TABLE_PROPERTY.DATATYPE
     * @mbggenerated Fri Jun 16 17:19:27 GMT+08:00 2017
     */
    public String getDatatype() {
        return datatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_TABLE_PROPERTY.DATATYPE
     *
     * @param datatype the value for SYSTEM_TABLE_PROPERTY.DATATYPE
     * @mbggenerated Fri Jun 16 17:19:27 GMT+08:00 2017
     */
    public void setDatatype(String datatype) {
        this.datatype = datatype == null ? null : datatype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_TABLE_PROPERTY.DATALENGTH
     *
     * @return the value of SYSTEM_TABLE_PROPERTY.DATALENGTH
     * @mbggenerated Fri Jun 16 17:19:27 GMT+08:00 2017
     */
    public int getDatalength() {
        return datalength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_TABLE_PROPERTY.DATALENGTH
     *
     * @param datalength the value for SYSTEM_TABLE_PROPERTY.DATALENGTH
     * @mbggenerated Fri Jun 16 17:19:27 GMT+08:00 2017
     */
    public void setDatalength(int datalength) {
        this.datalength = datalength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_TABLE_PROPERTY.ISNULL
     *
     * @return the value of SYSTEM_TABLE_PROPERTY.ISNULL
     * @mbggenerated Fri Jun 16 17:19:27 GMT+08:00 2017
     */
    public String getIsnull() {
        return isnull;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_TABLE_PROPERTY.ISNULL
     *
     * @param isnull the value for SYSTEM_TABLE_PROPERTY.ISNULL
     * @mbggenerated Fri Jun 16 17:19:27 GMT+08:00 2017
     */
    public void setIsnull(String isnull) {
        this.isnull = isnull;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_TABLE_PROPERTY.DEFAULTVALUE
     *
     * @return the value of SYSTEM_TABLE_PROPERTY.DEFAULTVALUE
     * @mbggenerated Fri Jun 16 17:19:27 GMT+08:00 2017
     */
    public String getDefaultvalue() {
        return defaultvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_TABLE_PROPERTY.DEFAULTVALUE
     *
     * @param defaultvalue the value for SYSTEM_TABLE_PROPERTY.DEFAULTVALUE
     * @mbggenerated Fri Jun 16 17:19:27 GMT+08:00 2017
     */
    public void setDefaultvalue(String defaultvalue) {
        this.defaultvalue = defaultvalue == null ? null : defaultvalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_TABLE_PROPERTY.PKEY
     *
     * @return the value of SYSTEM_TABLE_PROPERTY.PKEY
     * @mbggenerated Fri Jun 16 17:19:27 GMT+08:00 2017
     */
    public int getPkey() {
        return pkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_TABLE_PROPERTY.PKEY
     *
     * @param pkey the value for SYSTEM_TABLE_PROPERTY.PKEY
     * @mbggenerated Fri Jun 16 17:19:27 GMT+08:00 2017
     */
    public void setPkey(int pkey) {
        this.pkey = pkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_TABLE_PROPERTY.POINTLENGTH
     *
     * @return the value of SYSTEM_TABLE_PROPERTY.POINTLENGTH
     * @mbggenerated Fri Jun 16 17:19:27 GMT+08:00 2017
     */
    public int getPointlength() {
        return pointlength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_TABLE_PROPERTY.POINTLENGTH
     *
     * @param pointlength the value for SYSTEM_TABLE_PROPERTY.POINTLENGTH
     * @mbggenerated Fri Jun 16 17:19:27 GMT+08:00 2017
     */
    public void setPointlength(int pointlength) {
        this.pointlength = pointlength;
    }



}