package com.zkzy.portal.base.admin.api.entity;

import java.io.Serializable;

public class SystemNavigation implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_NAVIGATION.ID
     *
     * @mbggenerated Tue Sep 26 13:01:13 GMT+08:00 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_NAVIGATION.USERID
     *
     * @mbggenerated Tue Sep 26 13:01:13 GMT+08:00 2017
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_NAVIGATION.CREATEDATE
     *
     * @mbggenerated Tue Sep 26 13:01:13 GMT+08:00 2017
     */
    private String createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_NAVIGATION.UPDATETIME
     *
     * @mbggenerated Tue Sep 26 13:01:13 GMT+08:00 2017
     */
    private String updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_NAVIGATION.BACKIMG_URL
     *
     * @mbggenerated Tue Sep 26 13:01:13 GMT+08:00 2017
     */
    private String backimgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_NAVIGATION.GRIDSTER
     *
     * @mbggenerated Tue Sep 26 13:01:13 GMT+08:00 2017
     */
    private byte[] gridster;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_NAVIGATION.HTML
     *
     * @mbggenerated Tue Sep 26 13:01:13 GMT+08:00 2017
     */
    private byte[] html;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_NAVIGATION.ID
     *
     * @return the value of SYSTEM_NAVIGATION.ID
     *
     * @mbggenerated Tue Sep 26 13:01:13 GMT+08:00 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_NAVIGATION.ID
     *
     * @param id the value for SYSTEM_NAVIGATION.ID
     *
     * @mbggenerated Tue Sep 26 13:01:13 GMT+08:00 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_NAVIGATION.USERID
     *
     * @return the value of SYSTEM_NAVIGATION.USERID
     *
     * @mbggenerated Tue Sep 26 13:01:13 GMT+08:00 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_NAVIGATION.USERID
     *
     * @param userid the value for SYSTEM_NAVIGATION.USERID
     *
     * @mbggenerated Tue Sep 26 13:01:13 GMT+08:00 2017
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_NAVIGATION.CREATEDATE
     *
     * @return the value of SYSTEM_NAVIGATION.CREATEDATE
     *
     * @mbggenerated Tue Sep 26 13:01:13 GMT+08:00 2017
     */
    public String getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_NAVIGATION.CREATEDATE
     *
     * @param createdate the value for SYSTEM_NAVIGATION.CREATEDATE
     *
     * @mbggenerated Tue Sep 26 13:01:13 GMT+08:00 2017
     */
    public void setCreatedate(String createdate) {
        this.createdate = createdate == null ? null : createdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_NAVIGATION.UPDATETIME
     *
     * @return the value of SYSTEM_NAVIGATION.UPDATETIME
     *
     * @mbggenerated Tue Sep 26 13:01:13 GMT+08:00 2017
     */
    public String getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_NAVIGATION.UPDATETIME
     *
     * @param updatetime the value for SYSTEM_NAVIGATION.UPDATETIME
     *
     * @mbggenerated Tue Sep 26 13:01:13 GMT+08:00 2017
     */
    public void setUpdatetime(String updatetime) {
        this.updatetime = updatetime == null ? null : updatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_NAVIGATION.BACKIMG_URL
     *
     * @return the value of SYSTEM_NAVIGATION.BACKIMG_URL
     *
     * @mbggenerated Tue Sep 26 13:01:13 GMT+08:00 2017
     */
    public String getBackimgUrl() {
        return backimgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_NAVIGATION.BACKIMG_URL
     *
     * @param backimgUrl the value for SYSTEM_NAVIGATION.BACKIMG_URL
     *
     * @mbggenerated Tue Sep 26 13:01:13 GMT+08:00 2017
     */
    public void setBackimgUrl(String backimgUrl) {
        this.backimgUrl = backimgUrl == null ? null : backimgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_NAVIGATION.GRIDSTER
     *
     * @return the value of SYSTEM_NAVIGATION.GRIDSTER
     *
     * @mbggenerated Tue Sep 26 13:01:13 GMT+08:00 2017
     */
    public byte[] getGridster() {
        return gridster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_NAVIGATION.GRIDSTER
     *
     * @param gridster the value for SYSTEM_NAVIGATION.GRIDSTER
     *
     * @mbggenerated Tue Sep 26 13:01:13 GMT+08:00 2017
     */
    public void setGridster(byte[] gridster) {
        this.gridster = gridster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_NAVIGATION.HTML
     *
     * @return the value of SYSTEM_NAVIGATION.HTML
     *
     * @mbggenerated Tue Sep 26 13:01:13 GMT+08:00 2017
     */
    public byte[] getHtml() {
        return html;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_NAVIGATION.HTML
     *
     * @param html the value for SYSTEM_NAVIGATION.HTML
     *
     * @mbggenerated Tue Sep 26 13:01:13 GMT+08:00 2017
     */
    public void setHtml(byte[] html) {
        this.html = html;
    }
}