package com.zkzy.portal.base.admin.api.entity;

import java.util.Date;

public class SystemRoleMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ROLE_MENU.ID
     *
     * @mbggenerated Mon Apr 24 16:28:14 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ROLE_MENU.ROLE_ID
     *
     * @mbggenerated Mon Apr 24 16:28:14 CST 2017
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ROLE_MENU.PERMISSION_ID
     *
     * @mbggenerated Mon Apr 24 16:28:14 CST 2017
     */
    private Long permissionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ROLE_MENU.STATUS
     *
     * @mbggenerated Mon Apr 24 16:28:14 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ROLE_MENU.CREATE_DATE
     *
     * @mbggenerated Mon Apr 24 16:28:14 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ROLE_MENU.UPDATE_DATE
     *
     * @mbggenerated Mon Apr 24 16:28:14 CST 2017
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ROLE_MENU.ID
     *
     * @return the value of SYSTEM_ROLE_MENU.ID
     *
     * @mbggenerated Mon Apr 24 16:28:14 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ROLE_MENU.ID
     *
     * @param id the value for SYSTEM_ROLE_MENU.ID
     *
     * @mbggenerated Mon Apr 24 16:28:14 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ROLE_MENU.ROLE_ID
     *
     * @return the value of SYSTEM_ROLE_MENU.ROLE_ID
     *
     * @mbggenerated Mon Apr 24 16:28:14 CST 2017
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ROLE_MENU.ROLE_ID
     *
     * @param roleId the value for SYSTEM_ROLE_MENU.ROLE_ID
     *
     * @mbggenerated Mon Apr 24 16:28:14 CST 2017
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ROLE_MENU.PERMISSION_ID
     *
     * @return the value of SYSTEM_ROLE_MENU.PERMISSION_ID
     *
     * @mbggenerated Mon Apr 24 16:28:14 CST 2017
     */
    public Long getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ROLE_MENU.PERMISSION_ID
     *
     * @param permissionId the value for SYSTEM_ROLE_MENU.PERMISSION_ID
     *
     * @mbggenerated Mon Apr 24 16:28:14 CST 2017
     */
    public void setPermissionId(Long permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ROLE_MENU.STATUS
     *
     * @return the value of SYSTEM_ROLE_MENU.STATUS
     *
     * @mbggenerated Mon Apr 24 16:28:14 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ROLE_MENU.STATUS
     *
     * @param status the value for SYSTEM_ROLE_MENU.STATUS
     *
     * @mbggenerated Mon Apr 24 16:28:14 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ROLE_MENU.CREATE_DATE
     *
     * @return the value of SYSTEM_ROLE_MENU.CREATE_DATE
     *
     * @mbggenerated Mon Apr 24 16:28:14 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ROLE_MENU.CREATE_DATE
     *
     * @param createDate the value for SYSTEM_ROLE_MENU.CREATE_DATE
     *
     * @mbggenerated Mon Apr 24 16:28:14 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ROLE_MENU.UPDATE_DATE
     *
     * @return the value of SYSTEM_ROLE_MENU.UPDATE_DATE
     *
     * @mbggenerated Mon Apr 24 16:28:14 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ROLE_MENU.UPDATE_DATE
     *
     * @param updateDate the value for SYSTEM_ROLE_MENU.UPDATE_DATE
     *
     * @mbggenerated Mon Apr 24 16:28:14 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}