package com.zkzy.portal.base.admin.api.entity;

import java.io.Serializable;

public class SystemUserOrganization implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_USER_ORGANIZATION.ID
     *
     * @mbggenerated Wed Jun 21 09:34:31 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_USER_ORGANIZATION.USERID
     *
     * @mbggenerated Wed Jun 21 09:34:31 CST 2017
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_USER_ORGANIZATION.ORGANIZATIONID
     *
     * @mbggenerated Wed Jun 21 09:34:31 CST 2017
     */
    private String organizationid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_USER_ORGANIZATION.ID
     *
     * @return the value of SYSTEM_USER_ORGANIZATION.ID
     *
     * @mbggenerated Wed Jun 21 09:34:31 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_USER_ORGANIZATION.ID
     *
     * @param id the value for SYSTEM_USER_ORGANIZATION.ID
     *
     * @mbggenerated Wed Jun 21 09:34:31 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_USER_ORGANIZATION.USERID
     *
     * @return the value of SYSTEM_USER_ORGANIZATION.USERID
     *
     * @mbggenerated Wed Jun 21 09:34:31 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_USER_ORGANIZATION.USERID
     *
     * @param userid the value for SYSTEM_USER_ORGANIZATION.USERID
     *
     * @mbggenerated Wed Jun 21 09:34:31 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_USER_ORGANIZATION.ORGANIZATIONID
     *
     * @return the value of SYSTEM_USER_ORGANIZATION.ORGANIZATIONID
     *
     * @mbggenerated Wed Jun 21 09:34:31 CST 2017
     */
    public String getOrganizationid() {
        return organizationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_USER_ORGANIZATION.ORGANIZATIONID
     *
     * @param organizationid the value for SYSTEM_USER_ORGANIZATION.ORGANIZATIONID
     *
     * @mbggenerated Wed Jun 21 09:34:31 CST 2017
     */
    public void setOrganizationid(String organizationid) {
        this.organizationid = organizationid == null ? null : organizationid.trim();
    }
}