package com.zkzy.portal.base.admin.api.entity;

import java.io.Serializable;
import java.util.Date;

public class SystemParameter implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_PARAMETER.PARAMETER_ID
     *
     * @mbggenerated Mon Apr 17 11:23:35 CST 2017
     */
    private Long parameterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_PARAMETER.MYID
     *
     * @mbggenerated Mon Apr 17 11:23:35 CST 2017
     */
    private String myid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_PARAMETER.NAME
     *
     * @mbggenerated Mon Apr 17 11:23:35 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_PARAMETER.VALUE
     *
     * @mbggenerated Mon Apr 17 11:23:35 CST 2017
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_PARAMETER.DESCRIPTION
     *
     * @mbggenerated Mon Apr 17 11:23:35 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_PARAMETER.STATE
     *
     * @mbggenerated Mon Apr 17 11:23:35 CST 2017
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_PARAMETER.EDITOR
     *
     * @mbggenerated Mon Apr 17 11:23:35 CST 2017
     */
    private String editor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_PARAMETER.EDITOR_TYPE
     *
     * @mbggenerated Mon Apr 17 11:23:35 CST 2017
     */
    private String editorType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_PARAMETER.GROUP_TYPE
     *
     * @mbggenerated Mon Apr 17 11:23:35 CST 2017
     */
    private String groupType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_PARAMETER.STATUS
     *
     * @mbggenerated Mon Apr 17 11:23:35 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_PARAMETER.CREATED
     *
     * @mbggenerated Mon Apr 17 11:23:35 CST 2017
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_PARAMETER.LASTMOD
     *
     * @mbggenerated Mon Apr 17 11:23:35 CST 2017
     */
    private Date lastmod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_PARAMETER.CREATER
     *
     * @mbggenerated Mon Apr 17 11:23:35 CST 2017
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_PARAMETER.MODIFYER
     *
     * @mbggenerated Mon Apr 17 11:23:35 CST 2017
     */
    private String modifyer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_PARAMETER.PARAMETER_ID
     *
     * @return the value of SYSTEM_PARAMETER.PARAMETER_ID
     *
     * @mbggenerated Mon Apr 17 11:23:35 CST 2017
     */
    public Long getParameterId() {
        return parameterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_PARAMETER.PARAMETER_ID
     *
     * @param parameterId the value for SYSTEM_PARAMETER.PARAMETER_ID
     *
     * @mbggenerated Mon Apr 17 11:23:35 CST 2017
     */
    public void setParameterId(Long parameterId) {
        this.parameterId = parameterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_PARAMETER.MYID
     *
     * @return the value of SYSTEM_PARAMETER.MYID
     *
     * @mbggenerated Mon Apr 17 11:23:35 CST 2017
     */
    public String getMyid() {
        return myid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_PARAMETER.MYID
     *
     * @param myid the value for SYSTEM_PARAMETER.MYID
     *
     * @mbggenerated Mon Apr 17 11:23:35 CST 2017
     */
    public void setMyid(String myid) {
        this.myid = myid == null ? null : myid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_PARAMETER.NAME
     *
     * @return the value of SYSTEM_PARAMETER.NAME
     *
     * @mbggenerated Mon Apr 17 11:23:35 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_PARAMETER.NAME
     *
     * @param name the value for SYSTEM_PARAMETER.NAME
     *
     * @mbggenerated Mon Apr 17 11:23:35 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_PARAMETER.VALUE
     *
     * @return the value of SYSTEM_PARAMETER.VALUE
     *
     * @mbggenerated Mon Apr 17 11:23:35 CST 2017
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_PARAMETER.VALUE
     *
     * @param value the value for SYSTEM_PARAMETER.VALUE
     *
     * @mbggenerated Mon Apr 17 11:23:35 CST 2017
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_PARAMETER.DESCRIPTION
     *
     * @return the value of SYSTEM_PARAMETER.DESCRIPTION
     *
     * @mbggenerated Mon Apr 17 11:23:35 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_PARAMETER.DESCRIPTION
     *
     * @param description the value for SYSTEM_PARAMETER.DESCRIPTION
     *
     * @mbggenerated Mon Apr 17 11:23:35 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_PARAMETER.STATE
     *
     * @return the value of SYSTEM_PARAMETER.STATE
     *
     * @mbggenerated Mon Apr 17 11:23:35 CST 2017
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_PARAMETER.STATE
     *
     * @param state the value for SYSTEM_PARAMETER.STATE
     *
     * @mbggenerated Mon Apr 17 11:23:35 CST 2017
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_PARAMETER.EDITOR
     *
     * @return the value of SYSTEM_PARAMETER.EDITOR
     *
     * @mbggenerated Mon Apr 17 11:23:35 CST 2017
     */
    public String getEditor() {
        return editor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_PARAMETER.EDITOR
     *
     * @param editor the value for SYSTEM_PARAMETER.EDITOR
     *
     * @mbggenerated Mon Apr 17 11:23:35 CST 2017
     */
    public void setEditor(String editor) {
        this.editor = editor == null ? null : editor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_PARAMETER.EDITOR_TYPE
     *
     * @return the value of SYSTEM_PARAMETER.EDITOR_TYPE
     *
     * @mbggenerated Mon Apr 17 11:23:35 CST 2017
     */
    public String getEditorType() {
        return editorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_PARAMETER.EDITOR_TYPE
     *
     * @param editorType the value for SYSTEM_PARAMETER.EDITOR_TYPE
     *
     * @mbggenerated Mon Apr 17 11:23:35 CST 2017
     */
    public void setEditorType(String editorType) {
        this.editorType = editorType == null ? null : editorType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_PARAMETER.GROUP_TYPE
     *
     * @return the value of SYSTEM_PARAMETER.GROUP_TYPE
     *
     * @mbggenerated Mon Apr 17 11:23:35 CST 2017
     */
    public String getGroupType() {
        return groupType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_PARAMETER.GROUP_TYPE
     *
     * @param groupType the value for SYSTEM_PARAMETER.GROUP_TYPE
     *
     * @mbggenerated Mon Apr 17 11:23:35 CST 2017
     */
    public void setGroupType(String groupType) {
        this.groupType = groupType == null ? null : groupType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_PARAMETER.STATUS
     *
     * @return the value of SYSTEM_PARAMETER.STATUS
     *
     * @mbggenerated Mon Apr 17 11:23:35 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_PARAMETER.STATUS
     *
     * @param status the value for SYSTEM_PARAMETER.STATUS
     *
     * @mbggenerated Mon Apr 17 11:23:35 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_PARAMETER.CREATED
     *
     * @return the value of SYSTEM_PARAMETER.CREATED
     *
     * @mbggenerated Mon Apr 17 11:23:35 CST 2017
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_PARAMETER.CREATED
     *
     * @param created the value for SYSTEM_PARAMETER.CREATED
     *
     * @mbggenerated Mon Apr 17 11:23:35 CST 2017
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_PARAMETER.LASTMOD
     *
     * @return the value of SYSTEM_PARAMETER.LASTMOD
     *
     * @mbggenerated Mon Apr 17 11:23:35 CST 2017
     */
    public Date getLastmod() {
        return lastmod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_PARAMETER.LASTMOD
     *
     * @param lastmod the value for SYSTEM_PARAMETER.LASTMOD
     *
     * @mbggenerated Mon Apr 17 11:23:35 CST 2017
     */
    public void setLastmod(Date lastmod) {
        this.lastmod = lastmod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_PARAMETER.CREATER
     *
     * @return the value of SYSTEM_PARAMETER.CREATER
     *
     * @mbggenerated Mon Apr 17 11:23:35 CST 2017
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_PARAMETER.CREATER
     *
     * @param creater the value for SYSTEM_PARAMETER.CREATER
     *
     * @mbggenerated Mon Apr 17 11:23:35 CST 2017
     */
    public void setCreater(String creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_PARAMETER.MODIFYER
     *
     * @return the value of SYSTEM_PARAMETER.MODIFYER
     *
     * @mbggenerated Mon Apr 17 11:23:35 CST 2017
     */
    public String getModifyer() {
        return modifyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_PARAMETER.MODIFYER
     *
     * @param modifyer the value for SYSTEM_PARAMETER.MODIFYER
     *
     * @mbggenerated Mon Apr 17 11:23:35 CST 2017
     */
    public void setModifyer(String modifyer) {
        this.modifyer = modifyer;
    }
}