package com.zkzy.portal.base.admin.api.entity;

import java.io.Serializable;
import java.util.Date;

public class SystemUploadnode implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_UPLOADNODE.ID
     *
     * @mbggenerated Tue Jul 11 10:39:23 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_UPLOADNODE.PARENT_ID
     *
     * @mbggenerated Tue Jul 11 10:39:23 CST 2017
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_UPLOADNODE.NAME
     *
     * @mbggenerated Tue Jul 11 10:39:23 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_UPLOADNODE.TYPE
     *
     * @mbggenerated Tue Jul 11 10:39:23 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_UPLOADNODE.CREATEDATE
     *
     * @mbggenerated Tue Jul 11 10:39:23 CST 2017
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_UPLOADNODE.UPDATEDATE
     *
     * @mbggenerated Tue Jul 11 10:39:23 CST 2017
     */
    private Date updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_UPLOADNODE.CREATER
     *
     * @mbggenerated Tue Jul 11 10:39:23 CST 2017
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_UPLOADNODE.MODIFYER
     *
     * @mbggenerated Tue Jul 11 10:39:23 CST 2017
     */
    private String modifyer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_UPLOADNODE.ID
     *
     * @return the value of SYSTEM_UPLOADNODE.ID
     *
     * @mbggenerated Tue Jul 11 10:39:23 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_UPLOADNODE.ID
     *
     * @param id the value for SYSTEM_UPLOADNODE.ID
     *
     * @mbggenerated Tue Jul 11 10:39:23 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_UPLOADNODE.PARENT_ID
     *
     * @return the value of SYSTEM_UPLOADNODE.PARENT_ID
     *
     * @mbggenerated Tue Jul 11 10:39:23 CST 2017
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_UPLOADNODE.PARENT_ID
     *
     * @param parentId the value for SYSTEM_UPLOADNODE.PARENT_ID
     *
     * @mbggenerated Tue Jul 11 10:39:23 CST 2017
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_UPLOADNODE.NAME
     *
     * @return the value of SYSTEM_UPLOADNODE.NAME
     *
     * @mbggenerated Tue Jul 11 10:39:23 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_UPLOADNODE.NAME
     *
     * @param name the value for SYSTEM_UPLOADNODE.NAME
     *
     * @mbggenerated Tue Jul 11 10:39:23 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_UPLOADNODE.TYPE
     *
     * @return the value of SYSTEM_UPLOADNODE.TYPE
     *
     * @mbggenerated Tue Jul 11 10:39:23 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_UPLOADNODE.TYPE
     *
     * @param type the value for SYSTEM_UPLOADNODE.TYPE
     *
     * @mbggenerated Tue Jul 11 10:39:23 CST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_UPLOADNODE.CREATEDATE
     *
     * @return the value of SYSTEM_UPLOADNODE.CREATEDATE
     *
     * @mbggenerated Tue Jul 11 10:39:23 CST 2017
     */
    public Object getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_UPLOADNODE.CREATEDATE
     *
     * @param createdate the value for SYSTEM_UPLOADNODE.CREATEDATE
     *
     * @mbggenerated Tue Jul 11 10:39:23 CST 2017
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_UPLOADNODE.UPDATEDATE
     *
     * @return the value of SYSTEM_UPLOADNODE.UPDATEDATE
     *
     * @mbggenerated Tue Jul 11 10:39:23 CST 2017
     */
    public Object getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_UPLOADNODE.UPDATEDATE
     *
     * @param updatedate the value for SYSTEM_UPLOADNODE.UPDATEDATE
     *
     * @mbggenerated Tue Jul 11 10:39:23 CST 2017
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_UPLOADNODE.CREATER
     *
     * @return the value of SYSTEM_UPLOADNODE.CREATER
     *
     * @mbggenerated Tue Jul 11 10:39:23 CST 2017
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_UPLOADNODE.CREATER
     *
     * @param creater the value for SYSTEM_UPLOADNODE.CREATER
     *
     * @mbggenerated Tue Jul 11 10:39:23 CST 2017
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_UPLOADNODE.MODIFYER
     *
     * @return the value of SYSTEM_UPLOADNODE.MODIFYER
     *
     * @mbggenerated Tue Jul 11 10:39:23 CST 2017
     */
    public String getModifyer() {
        return modifyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_UPLOADNODE.MODIFYER
     *
     * @param modifyer the value for SYSTEM_UPLOADNODE.MODIFYER
     *
     * @mbggenerated Tue Jul 11 10:39:23 CST 2017
     */
    public void setModifyer(String modifyer) {
        this.modifyer = modifyer == null ? null : modifyer.trim();
    }
}