package com.zkzy.portal.base.admin.api.entity;

import java.io.Serializable;
import java.util.Date;

public class SystemRole implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ROLE.ID
     *
     * @mbggenerated Mon Apr 24 09:22:37 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ROLE.NAME
     *
     * @mbggenerated Mon Apr 24 09:22:37 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ROLE.DESCRIPTION
     *
     * @mbggenerated Mon Apr 24 09:22:37 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ROLE.STATUS
     *
     * @mbggenerated Mon Apr 24 09:22:37 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ROLE.CREATEDATE
     *
     * @mbggenerated Mon Apr 24 09:22:37 CST 2017
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ROLE.UPDATEDATE
     *
     * @mbggenerated Mon Apr 24 09:22:37 CST 2017
     */
    private Date updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ROLE.SORT
     *
     * @mbggenerated Mon Apr 24 09:22:37 CST 2017
     */
    private Long sort;

    private String identification;

    private String jumppagepath;

    public String getJumppagepath() {
        return jumppagepath;
    }

    public void setJumppagepath(String jumppagepath) {
        this.jumppagepath = jumppagepath;
    }

    public String getJumppagename() {
        return jumppagename;
    }

    public void setJumppagename(String jumppagename) {
        this.jumppagename = jumppagename;
    }

    private String jumppagename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ROLE.ID
     *
     * @return the value of SYSTEM_ROLE.ID
     *
     * @mbggenerated Mon Apr 24 09:22:37 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ROLE.ID
     *
     * @param id the value for SYSTEM_ROLE.ID
     *
     * @mbggenerated Mon Apr 24 09:22:37 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ROLE.NAME
     *
     * @return the value of SYSTEM_ROLE.NAME
     *
     * @mbggenerated Mon Apr 24 09:22:37 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ROLE.NAME
     *
     * @param name the value for SYSTEM_ROLE.NAME
     *
     * @mbggenerated Mon Apr 24 09:22:37 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ROLE.DESCRIPTION
     *
     * @return the value of SYSTEM_ROLE.DESCRIPTION
     *
     * @mbggenerated Mon Apr 24 09:22:37 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ROLE.DESCRIPTION
     *
     * @param description the value for SYSTEM_ROLE.DESCRIPTION
     *
     * @mbggenerated Mon Apr 24 09:22:37 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ROLE.STATUS
     *
     * @return the value of SYSTEM_ROLE.STATUS
     *
     * @mbggenerated Mon Apr 24 09:22:37 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ROLE.STATUS
     *
     * @param status the value for SYSTEM_ROLE.STATUS
     *
     * @mbggenerated Mon Apr 24 09:22:37 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ROLE.CREATEDATE
     *
     * @return the value of SYSTEM_ROLE.CREATEDATE
     *
     * @mbggenerated Mon Apr 24 09:22:37 CST 2017
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ROLE.CREATEDATE
     *
     * @param createdate the value for SYSTEM_ROLE.CREATEDATE
     *
     * @mbggenerated Mon Apr 24 09:22:37 CST 2017
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ROLE.UPDATEDATE
     *
     * @return the value of SYSTEM_ROLE.UPDATEDATE
     *
     * @mbggenerated Mon Apr 24 09:22:37 CST 2017
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ROLE.UPDATEDATE
     *
     * @param updatedate the value for SYSTEM_ROLE.UPDATEDATE
     *
     * @mbggenerated Mon Apr 24 09:22:37 CST 2017
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ROLE.SORT
     *
     * @return the value of SYSTEM_ROLE.SORT
     *
     * @mbggenerated Mon Apr 24 09:22:37 CST 2017
     */
    public Long getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ROLE.SORT
     *
     * @param sort the value for SYSTEM_ROLE.SORT
     *
     * @mbggenerated Mon Apr 24 09:22:37 CST 2017
     */
    public void setSort(Long sort) {
        this.sort = sort;
    }

    public String getIdentification() {
        return identification;
    }

    public void setIdentification(String identification) {
        this.identification = identification;
    }

    public boolean getEnabled(){
        if(this.status!=null&&this.status.equals("1")){
            return true;
        }else{
            return false;
        }
    }
}