package com.zkzy.portal.base.admin.api.entity;

import java.io.Serializable;

public class SystemEditor implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_EDITOR.ID
     *
     * @mbggenerated Mon Jun 26 13:52:49 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_EDITOR.NAME
     *
     * @mbggenerated Mon Jun 26 13:52:49 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_EDITOR.DESCRIPTION
     *
     * @mbggenerated Mon Jun 26 13:52:49 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_EDITOR.CREATER
     *
     * @mbggenerated Mon Jun 26 13:52:49 CST 2017
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_EDITOR.CREATETIME
     *
     * @mbggenerated Mon Jun 26 13:52:49 CST 2017
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_EDITOR.MODIFYER
     *
     * @mbggenerated Mon Jun 26 13:52:49 CST 2017
     */
    private String modifyer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_EDITOR.LASTMODIFYTIME
     *
     * @mbggenerated Mon Jun 26 13:52:49 CST 2017
     */
    private String lastmodifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_EDITOR.ISSHOW
     *
     * @mbggenerated Mon Jun 26 13:52:49 CST 2017
     */
    private String isshow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_EDITOR.FILEURL
     *
     * @mbggenerated Mon Jun 26 13:52:49 CST 2017
     */
    private String fileurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_EDITOR.BASENAME
     *
     * @mbggenerated Mon Jun 26 13:52:49 CST 2017
     */
    private String basename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_EDITOR.CONTENT
     *
     * @mbggenerated Mon Jun 26 13:52:49 CST 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_EDITOR.ID
     *
     * @return the value of SYSTEM_EDITOR.ID
     *
     * @mbggenerated Mon Jun 26 13:52:49 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_EDITOR.ID
     *
     * @param id the value for SYSTEM_EDITOR.ID
     *
     * @mbggenerated Mon Jun 26 13:52:49 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_EDITOR.NAME
     *
     * @return the value of SYSTEM_EDITOR.NAME
     *
     * @mbggenerated Mon Jun 26 13:52:49 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_EDITOR.NAME
     *
     * @param name the value for SYSTEM_EDITOR.NAME
     *
     * @mbggenerated Mon Jun 26 13:52:49 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_EDITOR.DESCRIPTION
     *
     * @return the value of SYSTEM_EDITOR.DESCRIPTION
     *
     * @mbggenerated Mon Jun 26 13:52:49 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_EDITOR.DESCRIPTION
     *
     * @param description the value for SYSTEM_EDITOR.DESCRIPTION
     *
     * @mbggenerated Mon Jun 26 13:52:49 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_EDITOR.CREATER
     *
     * @return the value of SYSTEM_EDITOR.CREATER
     *
     * @mbggenerated Mon Jun 26 13:52:49 CST 2017
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_EDITOR.CREATER
     *
     * @param creater the value for SYSTEM_EDITOR.CREATER
     *
     * @mbggenerated Mon Jun 26 13:52:49 CST 2017
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_EDITOR.CREATETIME
     *
     * @return the value of SYSTEM_EDITOR.CREATETIME
     *
     * @mbggenerated Mon Jun 26 13:52:49 CST 2017
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_EDITOR.CREATETIME
     *
     * @param createtime the value for SYSTEM_EDITOR.CREATETIME
     *
     * @mbggenerated Mon Jun 26 13:52:49 CST 2017
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_EDITOR.MODIFYER
     *
     * @return the value of SYSTEM_EDITOR.MODIFYER
     *
     * @mbggenerated Mon Jun 26 13:52:49 CST 2017
     */
    public String getModifyer() {
        return modifyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_EDITOR.MODIFYER
     *
     * @param modifyer the value for SYSTEM_EDITOR.MODIFYER
     *
     * @mbggenerated Mon Jun 26 13:52:49 CST 2017
     */
    public void setModifyer(String modifyer) {
        this.modifyer = modifyer == null ? null : modifyer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_EDITOR.LASTMODIFYTIME
     *
     * @return the value of SYSTEM_EDITOR.LASTMODIFYTIME
     *
     * @mbggenerated Mon Jun 26 13:52:49 CST 2017
     */
    public String getLastmodifytime() {
        return lastmodifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_EDITOR.LASTMODIFYTIME
     *
     * @param lastmodifytime the value for SYSTEM_EDITOR.LASTMODIFYTIME
     *
     * @mbggenerated Mon Jun 26 13:52:49 CST 2017
     */
    public void setLastmodifytime(String lastmodifytime) {
        this.lastmodifytime = lastmodifytime == null ? null : lastmodifytime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_EDITOR.ISSHOW
     *
     * @return the value of SYSTEM_EDITOR.ISSHOW
     *
     * @mbggenerated Mon Jun 26 13:52:49 CST 2017
     */
    public String getIsshow() {
        return isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_EDITOR.ISSHOW
     *
     * @param isshow the value for SYSTEM_EDITOR.ISSHOW
     *
     * @mbggenerated Mon Jun 26 13:52:49 CST 2017
     */
    public void setIsshow(String isshow) {
        this.isshow = isshow == null ? null : isshow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_EDITOR.FILEURL
     *
     * @return the value of SYSTEM_EDITOR.FILEURL
     *
     * @mbggenerated Mon Jun 26 13:52:49 CST 2017
     */
    public String getFileurl() {
        return fileurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_EDITOR.FILEURL
     *
     * @param fileurl the value for SYSTEM_EDITOR.FILEURL
     *
     * @mbggenerated Mon Jun 26 13:52:49 CST 2017
     */
    public void setFileurl(String fileurl) {
        this.fileurl = fileurl == null ? null : fileurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_EDITOR.BASENAME
     *
     * @return the value of SYSTEM_EDITOR.BASENAME
     *
     * @mbggenerated Mon Jun 26 13:52:49 CST 2017
     */
    public String getBasename() {
        return basename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_EDITOR.BASENAME
     *
     * @param basename the value for SYSTEM_EDITOR.BASENAME
     *
     * @mbggenerated Mon Jun 26 13:52:49 CST 2017
     */
    public void setBasename(String basename) {
        this.basename = basename == null ? null : basename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_EDITOR.CONTENT
     *
     * @return the value of SYSTEM_EDITOR.CONTENT
     *
     * @mbggenerated Mon Jun 26 13:52:49 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_EDITOR.CONTENT
     *
     * @param content the value for SYSTEM_EDITOR.CONTENT
     *
     * @mbggenerated Mon Jun 26 13:52:49 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}