package com.zkzy.portal.base.admin.api.entity;

import java.io.Serializable;
import java.util.Date;

public class SystemDepartment implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_DEPARTMENT.DEPARTMENT_ID
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    private String departmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_DEPARTMENT.COMPANY_ID
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    private Long companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_DEPARTMENT.MYID
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    private String myid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_DEPARTMENT.PID
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    private String pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_DEPARTMENT.FULL_NAME
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    private String fullName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_DEPARTMENT.ENAME
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    private String ename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_DEPARTMENT.MANAGER
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    private Long manager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_DEPARTMENT.ICONCLS
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    private String iconcls;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_DEPARTMENT.STATE
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_DEPARTMENT.ASSISTANT_MANAGER
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    private Long assistantManager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_DEPARTMENT.EMP_QTY
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    private Long empQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_DEPARTMENT.STATUS
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_DEPARTMENT.CREATED
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_DEPARTMENT.LASTMOD
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    private Date lastmod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_DEPARTMENT.SHORT_NAME
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    private String shortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_DEPARTMENT.TEL
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_DEPARTMENT.FAX
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_DEPARTMENT.DESCRIPTION
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_DEPARTMENT.CREATER
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    private Long creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_DEPARTMENT.MODIFYER
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    private Long modifyer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_DEPARTMENT.DEPARTMENT_ID
     *
     * @return the value of SYSTEM_DEPARTMENT.DEPARTMENT_ID
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    public String getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_DEPARTMENT.DEPARTMENT_ID
     *
     * @param departmentId the value for SYSTEM_DEPARTMENT.DEPARTMENT_ID
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId == null ? null : departmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_DEPARTMENT.COMPANY_ID
     *
     * @return the value of SYSTEM_DEPARTMENT.COMPANY_ID
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_DEPARTMENT.COMPANY_ID
     *
     * @param companyId the value for SYSTEM_DEPARTMENT.COMPANY_ID
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_DEPARTMENT.MYID
     *
     * @return the value of SYSTEM_DEPARTMENT.MYID
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    public String getMyid() {
        return myid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_DEPARTMENT.MYID
     *
     * @param myid the value for SYSTEM_DEPARTMENT.MYID
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    public void setMyid(String myid) {
        this.myid = myid == null ? null : myid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_DEPARTMENT.PID
     *
     * @return the value of SYSTEM_DEPARTMENT.PID
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_DEPARTMENT.PID
     *
     * @param pid the value for SYSTEM_DEPARTMENT.PID
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_DEPARTMENT.FULL_NAME
     *
     * @return the value of SYSTEM_DEPARTMENT.FULL_NAME
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_DEPARTMENT.FULL_NAME
     *
     * @param fullName the value for SYSTEM_DEPARTMENT.FULL_NAME
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    public void setFullName(String fullName) {
        this.fullName = fullName == null ? null : fullName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_DEPARTMENT.ENAME
     *
     * @return the value of SYSTEM_DEPARTMENT.ENAME
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_DEPARTMENT.ENAME
     *
     * @param ename the value for SYSTEM_DEPARTMENT.ENAME
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    public void setEname(String ename) {
        this.ename = ename == null ? null : ename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_DEPARTMENT.MANAGER
     *
     * @return the value of SYSTEM_DEPARTMENT.MANAGER
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    public Long getManager() {
        return manager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_DEPARTMENT.MANAGER
     *
     * @param manager the value for SYSTEM_DEPARTMENT.MANAGER
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    public void setManager(Long manager) {
        this.manager = manager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_DEPARTMENT.ICONCLS
     *
     * @return the value of SYSTEM_DEPARTMENT.ICONCLS
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    public String getIconcls() {
        return iconcls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_DEPARTMENT.ICONCLS
     *
     * @param iconcls the value for SYSTEM_DEPARTMENT.ICONCLS
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    public void setIconcls(String iconcls) {
        this.iconcls = iconcls == null ? null : iconcls.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_DEPARTMENT.STATE
     *
     * @return the value of SYSTEM_DEPARTMENT.STATE
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_DEPARTMENT.STATE
     *
     * @param state the value for SYSTEM_DEPARTMENT.STATE
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_DEPARTMENT.ASSISTANT_MANAGER
     *
     * @return the value of SYSTEM_DEPARTMENT.ASSISTANT_MANAGER
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    public Long getAssistantManager() {
        return assistantManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_DEPARTMENT.ASSISTANT_MANAGER
     *
     * @param assistantManager the value for SYSTEM_DEPARTMENT.ASSISTANT_MANAGER
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    public void setAssistantManager(Long assistantManager) {
        this.assistantManager = assistantManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_DEPARTMENT.EMP_QTY
     *
     * @return the value of SYSTEM_DEPARTMENT.EMP_QTY
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    public Long getEmpQty() {
        return empQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_DEPARTMENT.EMP_QTY
     *
     * @param empQty the value for SYSTEM_DEPARTMENT.EMP_QTY
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    public void setEmpQty(Long empQty) {
        this.empQty = empQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_DEPARTMENT.STATUS
     *
     * @return the value of SYSTEM_DEPARTMENT.STATUS
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_DEPARTMENT.STATUS
     *
     * @param status the value for SYSTEM_DEPARTMENT.STATUS
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_DEPARTMENT.CREATED
     *
     * @return the value of SYSTEM_DEPARTMENT.CREATED
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_DEPARTMENT.CREATED
     *
     * @param created the value for SYSTEM_DEPARTMENT.CREATED
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_DEPARTMENT.LASTMOD
     *
     * @return the value of SYSTEM_DEPARTMENT.LASTMOD
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    public Date getLastmod() {
        return lastmod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_DEPARTMENT.LASTMOD
     *
     * @param lastmod the value for SYSTEM_DEPARTMENT.LASTMOD
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    public void setLastmod(Date lastmod) {
        this.lastmod = lastmod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_DEPARTMENT.SHORT_NAME
     *
     * @return the value of SYSTEM_DEPARTMENT.SHORT_NAME
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_DEPARTMENT.SHORT_NAME
     *
     * @param shortName the value for SYSTEM_DEPARTMENT.SHORT_NAME
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    public void setShortName(String shortName) {
        this.shortName = shortName == null ? null : shortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_DEPARTMENT.TEL
     *
     * @return the value of SYSTEM_DEPARTMENT.TEL
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_DEPARTMENT.TEL
     *
     * @param tel the value for SYSTEM_DEPARTMENT.TEL
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_DEPARTMENT.FAX
     *
     * @return the value of SYSTEM_DEPARTMENT.FAX
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_DEPARTMENT.FAX
     *
     * @param fax the value for SYSTEM_DEPARTMENT.FAX
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_DEPARTMENT.DESCRIPTION
     *
     * @return the value of SYSTEM_DEPARTMENT.DESCRIPTION
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_DEPARTMENT.DESCRIPTION
     *
     * @param description the value for SYSTEM_DEPARTMENT.DESCRIPTION
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_DEPARTMENT.CREATER
     *
     * @return the value of SYSTEM_DEPARTMENT.CREATER
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    public Long getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_DEPARTMENT.CREATER
     *
     * @param creater the value for SYSTEM_DEPARTMENT.CREATER
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    public void setCreater(Long creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_DEPARTMENT.MODIFYER
     *
     * @return the value of SYSTEM_DEPARTMENT.MODIFYER
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    public Long getModifyer() {
        return modifyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_DEPARTMENT.MODIFYER
     *
     * @param modifyer the value for SYSTEM_DEPARTMENT.MODIFYER
     *
     * @mbggenerated Thu Jan 18 17:17:18 CST 2018
     */
    public void setModifyer(Long modifyer) {
        this.modifyer = modifyer;
    }
}