//package com.zkzy.portal.dumu.server.system.provider.mapper.base;
//
//
//import com.zkzy.zyportal.system.api.entity.base.SystemCode;
//import org.apache.ibatis.annotations.Mapper;
//
//import java.util.List;
//
//@Mapper
//public interface SystemCodeMapper {
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table SYSTEM_CODE
//     *
//     * @mbggenerated Mon Apr 17 09:59:31 CST 2017
//     */
//    int insert(SystemCode record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table SYSTEM_CODE
//     *
//     * @mbggenerated Mon Apr 17 09:59:31 CST 2017
//     */
//    List<SystemCode> selectAll(String param);
//
//    int updateStateById(SystemCode systemCode);
//
//    int updateParamById(SystemCode systemCode);
//
//    int delParamById(SystemCode systemCode);
//
//    SystemCode selectCodeById(SystemCode systemCode);
//
//    SystemCode selectCodeByMyId(SystemCode systemCode);
//
//    List<SystemCode> selectPemisson(String param);
//
//    List<SystemCode> selectParentid(String param);
//
//    List<SystemCode> selectTaskById(SystemCode systemCode);
//
//}