//package com.zkzy.portal.dumu.server.system.provider.mapper.base;
//
//
//import com.zkzy.zyportal.system.api.entity.base.SystemParameter;
//import org.apache.ibatis.annotations.Mapper;
//
//import java.util.List;
//
//@Mapper
//public interface SystemParameterMapper {
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table SYSTEM_PARAMETER
//     *
//     * @mbggenerated Mon Apr 17 11:23:35 CST 2017
//     */
//    int insert(SystemParameter record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table SYSTEM_PARAMETER
//     *
//     * @mbggenerated Mon Apr 17 11:23:35 CST 2017
//     */
//    List<SystemParameter> selectAll(String param);
//
//    List<SystemParameter> selectParams(String param);
//    /**
//     * 查询分组
//     * @return
//     */
//    List<SystemParameter> selectGroup();
//
//    /**
//     * 查找序列
//     * @return
//     */
//    String selectsequence();
//
//    /**
//     * 更新参数信息
//     * @param parameter
//     * @return
//     */
//    int updateParamById(SystemParameter parameter);
//    /**
//     * 根据Id查找
//     */
//    SystemParameter selectAllById(SystemParameter parameter);
//
//    int delparamById(SystemParameter parameter);
//
//    SystemParameter selectByMyID(String MyId);
//}