//package com.zkzy.portal.dumu.server.system.provider.mapper.base;
//
//import com.zkzy.zyportal.system.api.entity.base.SystemUserOrganization;
//import org.apache.ibatis.annotations.Mapper;
//
//import java.util.List;
//
//@Mapper
//public interface SystemUserOrganizationMapper {
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table SYSTEM_USER_ORGANIZATION
//     *
//     * @mbggenerated Wed Jun 21 09:34:31 CST 2017
//     */
//    int deleteByPrimaryKey(String id);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table SYSTEM_USER_ORGANIZATION
//     *
//     * @mbggenerated Wed Jun 21 09:34:31 CST 2017
//     */
//    int insert(SystemUserOrganization record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table SYSTEM_USER_ORGANIZATION
//     *
//     * @mbggenerated Wed Jun 21 09:34:31 CST 2017
//     */
//    SystemUserOrganization selectByPrimaryKey(String id);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table SYSTEM_USER_ORGANIZATION
//     *
//     * @mbggenerated Wed Jun 21 09:34:31 CST 2017
//     */
//    List<SystemUserOrganization> selectAll(String param);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table SYSTEM_USER_ORGANIZATION
//     *
//     * @mbggenerated Wed Jun 21 09:34:31 CST 2017
//     */
//    int updateByPrimaryKey(SystemUserOrganization record);
//
//
//    void delByUserId(String userId);
//
//}