package com.zkzy.portal.base.admin.api.viewModel;


import java.io.Serializable;

/**
 * Created by Thinkpad on 2018/1/8.
 */
public class BlackWaterInfos implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FC_BLACKANDSMELLYWATER_B.ID
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FC_BLACKANDSMELLYWATER_B.RIVERID
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    private String riverid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FC_BLACKANDSMELLYWATER_B.IMPLYEAR
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    private String implyear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FC_BLACKANDSMELLYWATER_B.RECTIFICATION
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    private String rectification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FC_BLACKANDSMELLYWATER_B.LONGITUDE
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    private String longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FC_BLACKANDSMELLYWATER_B.LATITUDE
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    private String latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FC_BLACKANDSMELLYWATER_B.RESTARTTIME
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    private String restarttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FC_BLACKANDSMELLYWATER_B.REENDTIME
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    private String reendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FC_BLACKANDSMELLYWATER_B.SEWAGETYPE
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    private String sewagetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FC_BLACKANDSMELLYWATER_B.REMARKS
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FC_BLACKANDSMELLYWATER_B.CREATETIME
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FC_BLACKANDSMELLYWATER_B.LASTMODTIME
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    private String lastmodtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FC_BLACKANDSMELLYWATER_B.COMPANY
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FC_BLACKANDSMELLYWATER_B.RIVERLENGTH
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    private Double riverlength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FC_BLACKANDSMELLYWATER_B.PLANNEDINVESTMENT
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    private String plannedinvestment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FC_BLACKANDSMELLYWATER_B.COMPINVESTMENT
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    private String compinvestment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FC_BLACKANDSMELLYWATER_B.MAKEPRO
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    private String makepro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FC_BLACKANDSMELLYWATER_B.TENDER
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    private String tender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FC_BLACKANDSMELLYWATER_B.CONSTRUCTION
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    private String construction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FC_BLACKANDSMELLYWATER_B.FINISHED
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    private String finished;

private  String rivername;

private String basin;

private  String username;

private  String post;

private  String basinstr;

    private String  sewagename;

    public String getSewagename() {
        return sewagename;
    }

    public void setSewagename(String sewagename) {
        this.sewagename = sewagename;
    }

    public String getBasin() {
        return basin;
    }

    public void setBasin(String basin) {
        this.basin = basin;
    }

    public String getBasinstr() {
        return basinstr;
    }

    public void setBasinstr(String basinstr) {
        this.basinstr = basinstr;
    }

    private  String companyname;

    public String getCompanyname() {
        return companyname;
    }

    public void setCompanyname(String companyname) {
        this.companyname = companyname;
    }


    private  String codename;

    public String getCodename() {
        return codename;
    }

    public void setCodename(String codename) {
        this.codename = codename;
    }



    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPost() {
        return post;
    }

    public void setPost(String post) {
        this.post = post;
    }

    public String getRivername() {
        return rivername;
    }

    public void setRivername(String rivername) {
        this.rivername = rivername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FC_BLACKANDSMELLYWATER_B.ID
     *
     * @return the value of FC_BLACKANDSMELLYWATER_B.ID
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FC_BLACKANDSMELLYWATER_B.ID
     *
     * @param id the value for FC_BLACKANDSMELLYWATER_B.ID
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FC_BLACKANDSMELLYWATER_B.RIVERID
     *
     * @return the value of FC_BLACKANDSMELLYWATER_B.RIVERID
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    public String getRiverid() {
        return riverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FC_BLACKANDSMELLYWATER_B.RIVERID
     *
     * @param riverid the value for FC_BLACKANDSMELLYWATER_B.RIVERID
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    public void setRiverid(String riverid) {
        this.riverid = riverid == null ? null : riverid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FC_BLACKANDSMELLYWATER_B.IMPLYEAR
     *
     * @return the value of FC_BLACKANDSMELLYWATER_B.IMPLYEAR
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    public String getImplyear() {
        return implyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FC_BLACKANDSMELLYWATER_B.IMPLYEAR
     *
     * @param implyear the value for FC_BLACKANDSMELLYWATER_B.IMPLYEAR
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    public void setImplyear(String implyear) {
        this.implyear = implyear == null ? null : implyear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FC_BLACKANDSMELLYWATER_B.RECTIFICATION
     *
     * @return the value of FC_BLACKANDSMELLYWATER_B.RECTIFICATION
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    public String getRectification() {
        return rectification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FC_BLACKANDSMELLYWATER_B.RECTIFICATION
     *
     * @param rectification the value for FC_BLACKANDSMELLYWATER_B.RECTIFICATION
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    public void setRectification(String rectification) {
        this.rectification = rectification == null ? null : rectification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FC_BLACKANDSMELLYWATER_B.LONGITUDE
     *
     * @return the value of FC_BLACKANDSMELLYWATER_B.LONGITUDE
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FC_BLACKANDSMELLYWATER_B.LONGITUDE
     *
     * @param longitude the value for FC_BLACKANDSMELLYWATER_B.LONGITUDE
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FC_BLACKANDSMELLYWATER_B.LATITUDE
     *
     * @return the value of FC_BLACKANDSMELLYWATER_B.LATITUDE
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FC_BLACKANDSMELLYWATER_B.LATITUDE
     *
     * @param latitude the value for FC_BLACKANDSMELLYWATER_B.LATITUDE
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FC_BLACKANDSMELLYWATER_B.RESTARTTIME
     *
     * @return the value of FC_BLACKANDSMELLYWATER_B.RESTARTTIME
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    public String getRestarttime() {
        return restarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FC_BLACKANDSMELLYWATER_B.RESTARTTIME
     *
     * @param restarttime the value for FC_BLACKANDSMELLYWATER_B.RESTARTTIME
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    public void setRestarttime(String restarttime) {
        this.restarttime = restarttime == null ? null : restarttime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FC_BLACKANDSMELLYWATER_B.REENDTIME
     *
     * @return the value of FC_BLACKANDSMELLYWATER_B.REENDTIME
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    public String getReendtime() {
        return reendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FC_BLACKANDSMELLYWATER_B.REENDTIME
     *
     * @param reendtime the value for FC_BLACKANDSMELLYWATER_B.REENDTIME
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    public void setReendtime(String reendtime) {
        this.reendtime = reendtime == null ? null : reendtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FC_BLACKANDSMELLYWATER_B.SEWAGETYPE
     *
     * @return the value of FC_BLACKANDSMELLYWATER_B.SEWAGETYPE
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    public String getSewagetype() {
        return sewagetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FC_BLACKANDSMELLYWATER_B.SEWAGETYPE
     *
     * @param sewagetype the value for FC_BLACKANDSMELLYWATER_B.SEWAGETYPE
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    public void setSewagetype(String sewagetype) {
        this.sewagetype = sewagetype == null ? null : sewagetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FC_BLACKANDSMELLYWATER_B.REMARKS
     *
     * @return the value of FC_BLACKANDSMELLYWATER_B.REMARKS
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FC_BLACKANDSMELLYWATER_B.REMARKS
     *
     * @param remarks the value for FC_BLACKANDSMELLYWATER_B.REMARKS
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FC_BLACKANDSMELLYWATER_B.CREATETIME
     *
     * @return the value of FC_BLACKANDSMELLYWATER_B.CREATETIME
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FC_BLACKANDSMELLYWATER_B.CREATETIME
     *
     * @param createtime the value for FC_BLACKANDSMELLYWATER_B.CREATETIME
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FC_BLACKANDSMELLYWATER_B.LASTMODTIME
     *
     * @return the value of FC_BLACKANDSMELLYWATER_B.LASTMODTIME
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    public String getLastmodtime() {
        return lastmodtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FC_BLACKANDSMELLYWATER_B.LASTMODTIME
     *
     * @param lastmodtime the value for FC_BLACKANDSMELLYWATER_B.LASTMODTIME
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    public void setLastmodtime(String lastmodtime) {
        this.lastmodtime = lastmodtime == null ? null : lastmodtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FC_BLACKANDSMELLYWATER_B.COMPANY
     *
     * @return the value of FC_BLACKANDSMELLYWATER_B.COMPANY
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FC_BLACKANDSMELLYWATER_B.COMPANY
     *
     * @param company the value for FC_BLACKANDSMELLYWATER_B.COMPANY
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FC_BLACKANDSMELLYWATER_B.RIVERLENGTH
     *
     * @return the value of FC_BLACKANDSMELLYWATER_B.RIVERLENGTH
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    public Double getRiverlength() {
        return riverlength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FC_BLACKANDSMELLYWATER_B.RIVERLENGTH
     *
     * @param riverlength the value for FC_BLACKANDSMELLYWATER_B.RIVERLENGTH
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    public void setRiverlength(Double riverlength) {
        this.riverlength = riverlength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FC_BLACKANDSMELLYWATER_B.PLANNEDINVESTMENT
     *
     * @return the value of FC_BLACKANDSMELLYWATER_B.PLANNEDINVESTMENT
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    public String getPlannedinvestment() {
        return plannedinvestment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FC_BLACKANDSMELLYWATER_B.PLANNEDINVESTMENT
     *
     * @param plannedinvestment the value for FC_BLACKANDSMELLYWATER_B.PLANNEDINVESTMENT
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    public void setPlannedinvestment(String plannedinvestment) {
        this.plannedinvestment = plannedinvestment == null ? null : plannedinvestment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FC_BLACKANDSMELLYWATER_B.COMPINVESTMENT
     *
     * @return the value of FC_BLACKANDSMELLYWATER_B.COMPINVESTMENT
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    public String getCompinvestment() {
        return compinvestment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FC_BLACKANDSMELLYWATER_B.COMPINVESTMENT
     *
     * @param compinvestment the value for FC_BLACKANDSMELLYWATER_B.COMPINVESTMENT
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    public void setCompinvestment(String compinvestment) {
        this.compinvestment = compinvestment == null ? null : compinvestment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FC_BLACKANDSMELLYWATER_B.MAKEPRO
     *
     * @return the value of FC_BLACKANDSMELLYWATER_B.MAKEPRO
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    public String getMakepro() {
        return makepro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FC_BLACKANDSMELLYWATER_B.MAKEPRO
     *
     * @param makepro the value for FC_BLACKANDSMELLYWATER_B.MAKEPRO
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    public void setMakepro(String makepro) {
        this.makepro = makepro == null ? null : makepro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FC_BLACKANDSMELLYWATER_B.TENDER
     *
     * @return the value of FC_BLACKANDSMELLYWATER_B.TENDER
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    public String getTender() {
        return tender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FC_BLACKANDSMELLYWATER_B.TENDER
     *
     * @param tender the value for FC_BLACKANDSMELLYWATER_B.TENDER
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    public void setTender(String tender) {
        this.tender = tender == null ? null : tender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FC_BLACKANDSMELLYWATER_B.CONSTRUCTION
     *
     * @return the value of FC_BLACKANDSMELLYWATER_B.CONSTRUCTION
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    public String getConstruction() {
        return construction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FC_BLACKANDSMELLYWATER_B.CONSTRUCTION
     *
     * @param construction the value for FC_BLACKANDSMELLYWATER_B.CONSTRUCTION
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    public void setConstruction(String construction) {
        this.construction = construction == null ? null : construction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FC_BLACKANDSMELLYWATER_B.FINISHED
     *
     * @return the value of FC_BLACKANDSMELLYWATER_B.FINISHED
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    public String getFinished() {
        return finished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FC_BLACKANDSMELLYWATER_B.FINISHED
     *
     * @param finished the value for FC_BLACKANDSMELLYWATER_B.FINISHED
     *
     * @mbggenerated Wed Jan 03 16:02:47 GMT+08:00 2018
     */
    public void setFinished(String finished) {
        this.finished = finished == null ? null : finished.trim();
    }

}
