package com.zkzy.zyportal.system.api.entity.base;

import java.io.Serializable;
import java.math.BigDecimal;

public class ImDevelopAccount implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_DEVELOP_ACCOUNT.ID
     *
     * @mbggenerated Fri Jul 28 09:06:03 GMT+08:00 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_DEVELOP_ACCOUNT.SERVER_IP
     *
     * @mbggenerated Fri Jul 28 09:06:03 GMT+08:00 2017
     */
    private String serverIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_DEVELOP_ACCOUNT.SERVER_PORT
     *
     * @mbggenerated Fri Jul 28 09:06:03 GMT+08:00 2017
     */
    private BigDecimal serverPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_DEVELOP_ACCOUNT.SOFTVERSION
     *
     * @mbggenerated Fri Jul 28 09:06:03 GMT+08:00 2017
     */
    private String softversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_DEVELOP_ACCOUNT.BASEURL
     *
     * @mbggenerated Fri Jul 28 09:06:03 GMT+08:00 2017
     */
    private String baseurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_DEVELOP_ACCOUNT.ACCOUNT_SID
     *
     * @mbggenerated Fri Jul 28 09:06:03 GMT+08:00 2017
     */
    private String accountSid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_DEVELOP_ACCOUNT.AUTH_TOKEN
     *
     * @mbggenerated Fri Jul 28 09:06:03 GMT+08:00 2017
     */
    private String authToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_DEVELOP_ACCOUNT.APP_ID
     *
     * @mbggenerated Fri Jul 28 09:06:03 GMT+08:00 2017
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_DEVELOP_ACCOUNT.APP_TOKEN
     *
     * @mbggenerated Fri Jul 28 09:06:03 GMT+08:00 2017
     */
    private String appToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_DEVELOP_ACCOUNT.MEMO
     *
     * @mbggenerated Fri Jul 28 09:06:03 GMT+08:00 2017
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_DEVELOP_ACCOUNT.STATUS
     *
     * @mbggenerated Fri Jul 28 09:06:03 GMT+08:00 2017
     */
    private BigDecimal status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_DEVELOP_ACCOUNT.DISABLED
     *
     * @mbggenerated Fri Jul 28 09:06:03 GMT+08:00 2017
     */
    private BigDecimal disabled;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_DEVELOP_ACCOUNT.ID
     *
     * @return the value of IM_DEVELOP_ACCOUNT.ID
     *
     * @mbggenerated Fri Jul 28 09:06:03 GMT+08:00 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_DEVELOP_ACCOUNT.ID
     *
     * @param id the value for IM_DEVELOP_ACCOUNT.ID
     *
     * @mbggenerated Fri Jul 28 09:06:03 GMT+08:00 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_DEVELOP_ACCOUNT.SERVER_IP
     *
     * @return the value of IM_DEVELOP_ACCOUNT.SERVER_IP
     *
     * @mbggenerated Fri Jul 28 09:06:03 GMT+08:00 2017
     */
    public String getServerIp() {
        return serverIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_DEVELOP_ACCOUNT.SERVER_IP
     *
     * @param serverIp the value for IM_DEVELOP_ACCOUNT.SERVER_IP
     *
     * @mbggenerated Fri Jul 28 09:06:03 GMT+08:00 2017
     */
    public void setServerIp(String serverIp) {
        this.serverIp = serverIp == null ? null : serverIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_DEVELOP_ACCOUNT.SERVER_PORT
     *
     * @return the value of IM_DEVELOP_ACCOUNT.SERVER_PORT
     *
     * @mbggenerated Fri Jul 28 09:06:03 GMT+08:00 2017
     */
    public BigDecimal getServerPort() {
        return serverPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_DEVELOP_ACCOUNT.SERVER_PORT
     *
     * @param serverPort the value for IM_DEVELOP_ACCOUNT.SERVER_PORT
     *
     * @mbggenerated Fri Jul 28 09:06:03 GMT+08:00 2017
     */
    public void setServerPort(BigDecimal serverPort) {
        this.serverPort = serverPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_DEVELOP_ACCOUNT.SOFTVERSION
     *
     * @return the value of IM_DEVELOP_ACCOUNT.SOFTVERSION
     *
     * @mbggenerated Fri Jul 28 09:06:03 GMT+08:00 2017
     */
    public String getSoftversion() {
        return softversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_DEVELOP_ACCOUNT.SOFTVERSION
     *
     * @param softversion the value for IM_DEVELOP_ACCOUNT.SOFTVERSION
     *
     * @mbggenerated Fri Jul 28 09:06:03 GMT+08:00 2017
     */
    public void setSoftversion(String softversion) {
        this.softversion = softversion == null ? null : softversion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_DEVELOP_ACCOUNT.BASEURL
     *
     * @return the value of IM_DEVELOP_ACCOUNT.BASEURL
     *
     * @mbggenerated Fri Jul 28 09:06:03 GMT+08:00 2017
     */
    public String getBaseurl() {
        return baseurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_DEVELOP_ACCOUNT.BASEURL
     *
     * @param baseurl the value for IM_DEVELOP_ACCOUNT.BASEURL
     *
     * @mbggenerated Fri Jul 28 09:06:03 GMT+08:00 2017
     */
    public void setBaseurl(String baseurl) {
        this.baseurl = baseurl == null ? null : baseurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_DEVELOP_ACCOUNT.ACCOUNT_SID
     *
     * @return the value of IM_DEVELOP_ACCOUNT.ACCOUNT_SID
     *
     * @mbggenerated Fri Jul 28 09:06:03 GMT+08:00 2017
     */
    public String getAccountSid() {
        return accountSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_DEVELOP_ACCOUNT.ACCOUNT_SID
     *
     * @param accountSid the value for IM_DEVELOP_ACCOUNT.ACCOUNT_SID
     *
     * @mbggenerated Fri Jul 28 09:06:03 GMT+08:00 2017
     */
    public void setAccountSid(String accountSid) {
        this.accountSid = accountSid == null ? null : accountSid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_DEVELOP_ACCOUNT.AUTH_TOKEN
     *
     * @return the value of IM_DEVELOP_ACCOUNT.AUTH_TOKEN
     *
     * @mbggenerated Fri Jul 28 09:06:03 GMT+08:00 2017
     */
    public String getAuthToken() {
        return authToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_DEVELOP_ACCOUNT.AUTH_TOKEN
     *
     * @param authToken the value for IM_DEVELOP_ACCOUNT.AUTH_TOKEN
     *
     * @mbggenerated Fri Jul 28 09:06:03 GMT+08:00 2017
     */
    public void setAuthToken(String authToken) {
        this.authToken = authToken == null ? null : authToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_DEVELOP_ACCOUNT.APP_ID
     *
     * @return the value of IM_DEVELOP_ACCOUNT.APP_ID
     *
     * @mbggenerated Fri Jul 28 09:06:03 GMT+08:00 2017
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_DEVELOP_ACCOUNT.APP_ID
     *
     * @param appId the value for IM_DEVELOP_ACCOUNT.APP_ID
     *
     * @mbggenerated Fri Jul 28 09:06:03 GMT+08:00 2017
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_DEVELOP_ACCOUNT.APP_TOKEN
     *
     * @return the value of IM_DEVELOP_ACCOUNT.APP_TOKEN
     *
     * @mbggenerated Fri Jul 28 09:06:03 GMT+08:00 2017
     */
    public String getAppToken() {
        return appToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_DEVELOP_ACCOUNT.APP_TOKEN
     *
     * @param appToken the value for IM_DEVELOP_ACCOUNT.APP_TOKEN
     *
     * @mbggenerated Fri Jul 28 09:06:03 GMT+08:00 2017
     */
    public void setAppToken(String appToken) {
        this.appToken = appToken == null ? null : appToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_DEVELOP_ACCOUNT.MEMO
     *
     * @return the value of IM_DEVELOP_ACCOUNT.MEMO
     *
     * @mbggenerated Fri Jul 28 09:06:03 GMT+08:00 2017
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_DEVELOP_ACCOUNT.MEMO
     *
     * @param memo the value for IM_DEVELOP_ACCOUNT.MEMO
     *
     * @mbggenerated Fri Jul 28 09:06:03 GMT+08:00 2017
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_DEVELOP_ACCOUNT.STATUS
     *
     * @return the value of IM_DEVELOP_ACCOUNT.STATUS
     *
     * @mbggenerated Fri Jul 28 09:06:03 GMT+08:00 2017
     */
    public BigDecimal getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_DEVELOP_ACCOUNT.STATUS
     *
     * @param status the value for IM_DEVELOP_ACCOUNT.STATUS
     *
     * @mbggenerated Fri Jul 28 09:06:03 GMT+08:00 2017
     */
    public void setStatus(BigDecimal status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_DEVELOP_ACCOUNT.DISABLED
     *
     * @return the value of IM_DEVELOP_ACCOUNT.DISABLED
     *
     * @mbggenerated Fri Jul 28 09:06:03 GMT+08:00 2017
     */
    public BigDecimal getDisabled() {
        return disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_DEVELOP_ACCOUNT.DISABLED
     *
     * @param disabled the value for IM_DEVELOP_ACCOUNT.DISABLED
     *
     * @mbggenerated Fri Jul 28 09:06:03 GMT+08:00 2017
     */
    public void setDisabled(BigDecimal disabled) {
        this.disabled = disabled;
    }
}