package com.zkzy.zyportal.system.api.entity.base;

import java.io.Serializable;
import java.math.BigDecimal;

public class SocialContacts implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SOCIAL_CONTACTS.ID
     *
     * @mbggenerated Thu Jul 13 12:45:18 GMT+08:00 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SOCIAL_CONTACTS.SYSTEM_USER_ID
     *
     * @mbggenerated Thu Jul 13 12:45:18 GMT+08:00 2017
     */
    private String systemUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SOCIAL_CONTACTS.statusCode
     *
     * @mbggenerated Thu Jul 13 12:45:18 GMT+08:00 2017
     */
    private String statusCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SOCIAL_CONTACTS.subAccountSid
     *
     * @mbggenerated Thu Jul 13 12:45:18 GMT+08:00 2017
     */
    private String subAccountSid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SOCIAL_CONTACTS.subToken
     *
     * @mbggenerated Thu Jul 13 12:45:18 GMT+08:00 2017
     */
    private String subToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SOCIAL_CONTACTS.dateCreated
     *
     * @mbggenerated Thu Jul 13 12:45:18 GMT+08:00 2017
     */
    private String dateCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SOCIAL_CONTACTS.voipAccount
     *
     * @mbggenerated Thu Jul 13 12:45:18 GMT+08:00 2017
     */
    private String voipAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SOCIAL_CONTACTS.voipPwd
     *
     * @mbggenerated Thu Jul 13 12:45:18 GMT+08:00 2017
     */
    private String voipPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SOCIAL_CONTACTS.FRIENDLYNAME
     *
     * @mbggenerated Thu Jul 13 12:45:18 GMT+08:00 2017
     */
    private String friendlyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SOCIAL_CONTACTS.PHOTO
     *
     * @mbggenerated Thu Jul 13 12:45:18 GMT+08:00 2017
     */
    private String photo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SOCIAL_CONTACTS.STATUS
     *
     * @mbggenerated Thu Jul 13 12:45:18 GMT+08:00 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SOCIAL_CONTACTS.DISABLED
     *
     * @mbggenerated Thu Jul 13 12:45:18 GMT+08:00 2017
     */
    private BigDecimal disabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SOCIAL_CONTACTS.SHUOSHUO
     *
     * @mbggenerated Thu Jul 13 12:45:18 GMT+08:00 2017
     */
    private String shuoshuo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SOCIAL_CONTACTS.ID
     *
     * @return the value of SOCIAL_CONTACTS.ID
     * @mbggenerated Thu Jul 13 12:45:18 GMT+08:00 2017
     */

    private String account;

    public void setAccount(String account) {
        this.account = account;
    }

    public String getAccount() {
        return account;
    }

    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SOCIAL_CONTACTS.ID
     *
     * @param id the value for SOCIAL_CONTACTS.ID
     * @mbggenerated Thu Jul 13 12:45:18 GMT+08:00 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SOCIAL_CONTACTS.SYSTEM_USER_ID
     *
     * @return the value of SOCIAL_CONTACTS.SYSTEM_USER_ID
     * @mbggenerated Thu Jul 13 12:45:18 GMT+08:00 2017
     */
    public String getSystemUserId() {
        return systemUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SOCIAL_CONTACTS.SYSTEM_USER_ID
     *
     * @param systemUserId the value for SOCIAL_CONTACTS.SYSTEM_USER_ID
     * @mbggenerated Thu Jul 13 12:45:18 GMT+08:00 2017
     */
    public void setSystemUserId(String systemUserId) {
        this.systemUserId = systemUserId == null ? null : systemUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SOCIAL_CONTACTS.statusCode
     *
     * @return the value of SOCIAL_CONTACTS.statusCode
     * @mbggenerated Thu Jul 13 12:45:18 GMT+08:00 2017
     */
    public String getstatusCode() {
        return statusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SOCIAL_CONTACTS.statusCode
     *
     * @param statusCode the value for SOCIAL_CONTACTS.statusCode
     * @mbggenerated Thu Jul 13 12:45:18 GMT+08:00 2017
     */
    public void setstatusCode(String statusCode) {
        this.statusCode = statusCode == null ? null : statusCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SOCIAL_CONTACTS.subAccountSid
     *
     * @return the value of SOCIAL_CONTACTS.subAccountSid
     * @mbggenerated Thu Jul 13 12:45:18 GMT+08:00 2017
     */
    public String getsubAccountSid() {
        return subAccountSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SOCIAL_CONTACTS.subAccountSid
     *
     * @param subAccountSid the value for SOCIAL_CONTACTS.subAccountSid
     * @mbggenerated Thu Jul 13 12:45:18 GMT+08:00 2017
     */
    public void setsubAccountSid(String subAccountSid) {
        this.subAccountSid = subAccountSid == null ? null : subAccountSid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SOCIAL_CONTACTS.subToken
     *
     * @return the value of SOCIAL_CONTACTS.subToken
     * @mbggenerated Thu Jul 13 12:45:18 GMT+08:00 2017
     */
    public String getsubToken() {
        return subToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SOCIAL_CONTACTS.subToken
     *
     * @param subToken the value for SOCIAL_CONTACTS.subToken
     * @mbggenerated Thu Jul 13 12:45:18 GMT+08:00 2017
     */
    public void setsubToken(String subToken) {
        this.subToken = subToken == null ? null : subToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SOCIAL_CONTACTS.dateCreated
     *
     * @return the value of SOCIAL_CONTACTS.dateCreated
     * @mbggenerated Thu Jul 13 12:45:18 GMT+08:00 2017
     */
    public String getdateCreated() {
        return dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SOCIAL_CONTACTS.dateCreated
     *
     * @param dateCreated the value for SOCIAL_CONTACTS.dateCreated
     * @mbggenerated Thu Jul 13 12:45:18 GMT+08:00 2017
     */
    public void setdateCreated(String dateCreated) {
        this.dateCreated = dateCreated == null ? null : dateCreated.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SOCIAL_CONTACTS.voipAccount
     *
     * @return the value of SOCIAL_CONTACTS.voipAccount
     * @mbggenerated Thu Jul 13 12:45:18 GMT+08:00 2017
     */
    public String getvoipAccount() {
        return voipAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SOCIAL_CONTACTS.voipAccount
     *
     * @param voipAccount the value for SOCIAL_CONTACTS.voipAccount
     * @mbggenerated Thu Jul 13 12:45:18 GMT+08:00 2017
     */
    public void setvoipAccount(String voipAccount) {
        this.voipAccount = voipAccount == null ? null : voipAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SOCIAL_CONTACTS.voipPwd
     *
     * @return the value of SOCIAL_CONTACTS.voipPwd
     * @mbggenerated Thu Jul 13 12:45:18 GMT+08:00 2017
     */
    public String getvoipPwd() {
        return voipPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SOCIAL_CONTACTS.voipPwd
     *
     * @param voipPwd the value for SOCIAL_CONTACTS.voipPwd
     * @mbggenerated Thu Jul 13 12:45:18 GMT+08:00 2017
     */
    public void setvoipPwd(String voipPwd) {
        this.voipPwd = voipPwd == null ? null : voipPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SOCIAL_CONTACTS.FRIENDLYNAME
     *
     * @return the value of SOCIAL_CONTACTS.FRIENDLYNAME
     * @mbggenerated Thu Jul 13 12:45:18 GMT+08:00 2017
     */
    public String getFriendlyname() {
        return friendlyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SOCIAL_CONTACTS.FRIENDLYNAME
     *
     * @param friendlyname the value for SOCIAL_CONTACTS.FRIENDLYNAME
     * @mbggenerated Thu Jul 13 12:45:18 GMT+08:00 2017
     */
    public void setFriendlyname(String friendlyname) {
        this.friendlyname = friendlyname == null ? null : friendlyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SOCIAL_CONTACTS.PHOTO
     *
     * @return the value of SOCIAL_CONTACTS.PHOTO
     * @mbggenerated Thu Jul 13 12:45:18 GMT+08:00 2017
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SOCIAL_CONTACTS.PHOTO
     *
     * @param photo the value for SOCIAL_CONTACTS.PHOTO
     * @mbggenerated Thu Jul 13 12:45:18 GMT+08:00 2017
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SOCIAL_CONTACTS.STATUS
     *
     * @return the value of SOCIAL_CONTACTS.STATUS
     * @mbggenerated Thu Jul 13 12:45:18 GMT+08:00 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SOCIAL_CONTACTS.STATUS
     *
     * @param status the value for SOCIAL_CONTACTS.STATUS
     * @mbggenerated Thu Jul 13 12:45:18 GMT+08:00 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SOCIAL_CONTACTS.DISABLED
     *
     * @return the value of SOCIAL_CONTACTS.DISABLED
     * @mbggenerated Thu Jul 13 12:45:18 GMT+08:00 2017
     */
    public BigDecimal getDisabled() {
        return disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SOCIAL_CONTACTS.DISABLED
     *
     * @param disabled the value for SOCIAL_CONTACTS.DISABLED
     * @mbggenerated Thu Jul 13 12:45:18 GMT+08:00 2017
     */
    public void setDisabled(BigDecimal disabled) {
        this.disabled = disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SOCIAL_CONTACTS.SHUOSHUO
     *
     * @return the value of SOCIAL_CONTACTS.SHUOSHUO
     * @mbggenerated Thu Jul 13 12:45:18 GMT+08:00 2017
     */
    public String getShuoshuo() {
        return shuoshuo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SOCIAL_CONTACTS.SHUOSHUO
     *
     * @param shuoshuo the value for SOCIAL_CONTACTS.SHUOSHUO
     * @mbggenerated Thu Jul 13 12:45:18 GMT+08:00 2017
     */
    public void setShuoshuo(String shuoshuo) {
        this.shuoshuo = shuoshuo == null ? null : shuoshuo.trim();
    }


}