package com.zkzy.zyportal.system.api.entity.base;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;

public class SocialGroup implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SOCIAL_GROUP.ID
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SOCIAL_GROUP.GROUP_ID
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SOCIAL_GROUP.GROUP_NAME
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SOCIAL_GROUP.GROUP_DOMAIN
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    private String groupDomain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SOCIAL_GROUP.DECLARED
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    private String declared;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SOCIAL_GROUP.SCOPE
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    private BigDecimal scope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SOCIAL_GROUP.PERMISSION
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    private BigDecimal permission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SOCIAL_GROUP.TARGET
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    private BigDecimal target;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SOCIAL_GROUP.OWNER_ID
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    private String ownerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SOCIAL_GROUP.GROUP_MEMBER_COUNTS
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    private BigDecimal groupMemberCounts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SOCIAL_GROUP.CREATETIME
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SOCIAL_GROUP.UPDATETIME
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    private String updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SOCIAL_GROUP.STATUS_CODE
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    private BigDecimal statusCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SOCIAL_GROUP.GROUP_JOINED
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    private String groupJoined;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SOCIAL_GROUP.GROUP_ISNOTICE
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    private String groupIsnotice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SOCIAL_GROUP.GROUP_DISCUSSION
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    private String groupDiscussion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SOCIAL_GROUP.MEMBERS
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    private String members;

    private String ownerAccount;


    private List<SocialContacts> memberList;

    private SocialContacts owner;

    public void setOwnerAccount(String ownerAccount) {
        this.ownerAccount = ownerAccount;
    }

    public String getOwnerAccount() {
        return ownerAccount;
    }

    public void setOwner(SocialContacts owner) {
        this.owner = owner;
    }

    public SocialContacts getOwner() {
        return owner;
    }

    public void setMemberList(List<SocialContacts> memberList) {
        this.memberList = memberList;
    }

    public List<SocialContacts> getMemberList() {
        return memberList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SOCIAL_GROUP.ID
     *
     * @return the value of SOCIAL_GROUP.ID
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SOCIAL_GROUP.ID
     *
     * @param id the value for SOCIAL_GROUP.ID
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SOCIAL_GROUP.GROUP_ID
     *
     * @return the value of SOCIAL_GROUP.GROUP_ID
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SOCIAL_GROUP.GROUP_ID
     *
     * @param groupId the value for SOCIAL_GROUP.GROUP_ID
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SOCIAL_GROUP.GROUP_NAME
     *
     * @return the value of SOCIAL_GROUP.GROUP_NAME
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SOCIAL_GROUP.GROUP_NAME
     *
     * @param groupName the value for SOCIAL_GROUP.GROUP_NAME
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SOCIAL_GROUP.GROUP_DOMAIN
     *
     * @return the value of SOCIAL_GROUP.GROUP_DOMAIN
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    public String getGroupDomain() {
        return groupDomain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SOCIAL_GROUP.GROUP_DOMAIN
     *
     * @param groupDomain the value for SOCIAL_GROUP.GROUP_DOMAIN
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    public void setGroupDomain(String groupDomain) {
        this.groupDomain = groupDomain == null ? null : groupDomain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SOCIAL_GROUP.DECLARED
     *
     * @return the value of SOCIAL_GROUP.DECLARED
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    public String getDeclared() {
        return declared;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SOCIAL_GROUP.DECLARED
     *
     * @param declared the value for SOCIAL_GROUP.DECLARED
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    public void setDeclared(String declared) {
        this.declared = declared == null ? null : declared.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SOCIAL_GROUP.SCOPE
     *
     * @return the value of SOCIAL_GROUP.SCOPE
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    public BigDecimal getScope() {
        return scope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SOCIAL_GROUP.SCOPE
     *
     * @param scope the value for SOCIAL_GROUP.SCOPE
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    public void setScope(BigDecimal scope) {
        this.scope = scope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SOCIAL_GROUP.PERMISSION
     *
     * @return the value of SOCIAL_GROUP.PERMISSION
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    public BigDecimal getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SOCIAL_GROUP.PERMISSION
     *
     * @param permission the value for SOCIAL_GROUP.PERMISSION
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    public void setPermission(BigDecimal permission) {
        this.permission = permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SOCIAL_GROUP.TARGET
     *
     * @return the value of SOCIAL_GROUP.TARGET
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    public BigDecimal getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SOCIAL_GROUP.TARGET
     *
     * @param target the value for SOCIAL_GROUP.TARGET
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    public void setTarget(BigDecimal target) {
        this.target = target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SOCIAL_GROUP.OWNER_ID
     *
     * @return the value of SOCIAL_GROUP.OWNER_ID
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    public String getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SOCIAL_GROUP.OWNER_ID
     *
     * @param ownerId the value for SOCIAL_GROUP.OWNER_ID
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    public void setOwnerId(String ownerId) {
        this.ownerId = ownerId == null ? null : ownerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SOCIAL_GROUP.GROUP_MEMBER_COUNTS
     *
     * @return the value of SOCIAL_GROUP.GROUP_MEMBER_COUNTS
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    public BigDecimal getGroupMemberCounts() {
        return groupMemberCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SOCIAL_GROUP.GROUP_MEMBER_COUNTS
     *
     * @param groupMemberCounts the value for SOCIAL_GROUP.GROUP_MEMBER_COUNTS
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    public void setGroupMemberCounts(BigDecimal groupMemberCounts) {
        this.groupMemberCounts = groupMemberCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SOCIAL_GROUP.CREATETIME
     *
     * @return the value of SOCIAL_GROUP.CREATETIME
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SOCIAL_GROUP.CREATETIME
     *
     * @param createtime the value for SOCIAL_GROUP.CREATETIME
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SOCIAL_GROUP.UPDATETIME
     *
     * @return the value of SOCIAL_GROUP.UPDATETIME
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    public String getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SOCIAL_GROUP.UPDATETIME
     *
     * @param updatetime the value for SOCIAL_GROUP.UPDATETIME
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    public void setUpdatetime(String updatetime) {
        this.updatetime = updatetime == null ? null : updatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SOCIAL_GROUP.STATUS_CODE
     *
     * @return the value of SOCIAL_GROUP.STATUS_CODE
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    public BigDecimal getStatusCode() {
        return statusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SOCIAL_GROUP.STATUS_CODE
     *
     * @param statusCode the value for SOCIAL_GROUP.STATUS_CODE
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    public void setStatusCode(BigDecimal statusCode) {
        this.statusCode = statusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SOCIAL_GROUP.GROUP_JOINED
     *
     * @return the value of SOCIAL_GROUP.GROUP_JOINED
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    public String getGroupJoined() {
        return groupJoined;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SOCIAL_GROUP.GROUP_JOINED
     *
     * @param groupJoined the value for SOCIAL_GROUP.GROUP_JOINED
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    public void setGroupJoined(String groupJoined) {
        this.groupJoined = groupJoined == null ? null : groupJoined.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SOCIAL_GROUP.GROUP_ISNOTICE
     *
     * @return the value of SOCIAL_GROUP.GROUP_ISNOTICE
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    public String getGroupIsnotice() {
        return groupIsnotice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SOCIAL_GROUP.GROUP_ISNOTICE
     *
     * @param groupIsnotice the value for SOCIAL_GROUP.GROUP_ISNOTICE
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    public void setGroupIsnotice(String groupIsnotice) {
        this.groupIsnotice = groupIsnotice == null ? null : groupIsnotice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SOCIAL_GROUP.GROUP_DISCUSSION
     *
     * @return the value of SOCIAL_GROUP.GROUP_DISCUSSION
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    public String getGroupDiscussion() {
        return groupDiscussion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SOCIAL_GROUP.GROUP_DISCUSSION
     *
     * @param groupDiscussion the value for SOCIAL_GROUP.GROUP_DISCUSSION
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    public void setGroupDiscussion(String groupDiscussion) {
        this.groupDiscussion = groupDiscussion == null ? null : groupDiscussion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SOCIAL_GROUP.MEMBERS
     *
     * @return the value of SOCIAL_GROUP.MEMBERS
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    public String getMembers() {
        return members;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SOCIAL_GROUP.MEMBERS
     *
     * @param members the value for SOCIAL_GROUP.MEMBERS
     *
     * @mbggenerated Mon Jan 08 18:00:44 GMT+08:00 2018
     */
    public void setMembers(String members) {
        this.members = members == null ? null : members.trim();
    }

    @Override
    public String toString() {
        return super.toString();
    }
}