package com.zkzy.zyportal.system.api.entity.base;

import java.io.Serializable;
import java.util.Date;

public class SystemOrganization implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ORGANIZATION.ORGANIZATION_ID
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    private String organizationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ORGANIZATION.COMPANY_ID
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    private Long companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ORGANIZATION.MYID
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    private String myid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ORGANIZATION.PID
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    private String pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ORGANIZATION.FULL_NAME
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    private String fullName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ORGANIZATION.ENAME
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    private String ename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ORGANIZATION.MANAGER
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    private Long manager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ORGANIZATION.ICONCLS
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    private String iconcls;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ORGANIZATION.STATE
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ORGANIZATION.ASSISTANT_MANAGER
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    private Long assistantManager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ORGANIZATION.EMP_QTY
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    private Long empQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ORGANIZATION.STATUS
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ORGANIZATION.CREATED
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ORGANIZATION.LASTMOD
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    private Date lastmod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ORGANIZATION.SHORT_NAME
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    private String shortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ORGANIZATION.TEL
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ORGANIZATION.FAX
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ORGANIZATION.DESCRIPTION
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ORGANIZATION.CREATER
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    private Long creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_ORGANIZATION.MODIFYER
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    private Long modifyer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ORGANIZATION.ORGANIZATION_ID
     *
     * @return the value of SYSTEM_ORGANIZATION.ORGANIZATION_ID
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    public String getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ORGANIZATION.ORGANIZATION_ID
     *
     * @param organizationId the value for SYSTEM_ORGANIZATION.ORGANIZATION_ID
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    public void setOrganizationId(String organizationId) {
        this.organizationId = organizationId == null ? null : organizationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ORGANIZATION.COMPANY_ID
     *
     * @return the value of SYSTEM_ORGANIZATION.COMPANY_ID
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ORGANIZATION.COMPANY_ID
     *
     * @param companyId the value for SYSTEM_ORGANIZATION.COMPANY_ID
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ORGANIZATION.MYID
     *
     * @return the value of SYSTEM_ORGANIZATION.MYID
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    public String getMyid() {
        return myid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ORGANIZATION.MYID
     *
     * @param myid the value for SYSTEM_ORGANIZATION.MYID
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    public void setMyid(String myid) {
        this.myid = myid == null ? null : myid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ORGANIZATION.PID
     *
     * @return the value of SYSTEM_ORGANIZATION.PID
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ORGANIZATION.PID
     *
     * @param pid the value for SYSTEM_ORGANIZATION.PID
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    public void setPid(String pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ORGANIZATION.FULL_NAME
     *
     * @return the value of SYSTEM_ORGANIZATION.FULL_NAME
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ORGANIZATION.FULL_NAME
     *
     * @param fullName the value for SYSTEM_ORGANIZATION.FULL_NAME
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    public void setFullName(String fullName) {
        this.fullName = fullName == null ? null : fullName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ORGANIZATION.ENAME
     *
     * @return the value of SYSTEM_ORGANIZATION.ENAME
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ORGANIZATION.ENAME
     *
     * @param ename the value for SYSTEM_ORGANIZATION.ENAME
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    public void setEname(String ename) {
        this.ename = ename == null ? null : ename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ORGANIZATION.MANAGER
     *
     * @return the value of SYSTEM_ORGANIZATION.MANAGER
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    public Long getManager() {
        return manager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ORGANIZATION.MANAGER
     *
     * @param manager the value for SYSTEM_ORGANIZATION.MANAGER
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    public void setManager(Long manager) {
        this.manager = manager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ORGANIZATION.ICONCLS
     *
     * @return the value of SYSTEM_ORGANIZATION.ICONCLS
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    public String getIconcls() {
        return iconcls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ORGANIZATION.ICONCLS
     *
     * @param iconcls the value for SYSTEM_ORGANIZATION.ICONCLS
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    public void setIconcls(String iconcls) {
        this.iconcls = iconcls == null ? null : iconcls.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ORGANIZATION.STATE
     *
     * @return the value of SYSTEM_ORGANIZATION.STATE
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ORGANIZATION.STATE
     *
     * @param state the value for SYSTEM_ORGANIZATION.STATE
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ORGANIZATION.ASSISTANT_MANAGER
     *
     * @return the value of SYSTEM_ORGANIZATION.ASSISTANT_MANAGER
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    public Long getAssistantManager() {
        return assistantManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ORGANIZATION.ASSISTANT_MANAGER
     *
     * @param assistantManager the value for SYSTEM_ORGANIZATION.ASSISTANT_MANAGER
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    public void setAssistantManager(Long assistantManager) {
        this.assistantManager = assistantManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ORGANIZATION.EMP_QTY
     *
     * @return the value of SYSTEM_ORGANIZATION.EMP_QTY
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    public Long getEmpQty() {
        return empQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ORGANIZATION.EMP_QTY
     *
     * @param empQty the value for SYSTEM_ORGANIZATION.EMP_QTY
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    public void setEmpQty(Long empQty) {
        this.empQty = empQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ORGANIZATION.STATUS
     *
     * @return the value of SYSTEM_ORGANIZATION.STATUS
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ORGANIZATION.STATUS
     *
     * @param status the value for SYSTEM_ORGANIZATION.STATUS
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ORGANIZATION.CREATED
     *
     * @return the value of SYSTEM_ORGANIZATION.CREATED
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ORGANIZATION.CREATED
     *
     * @param created the value for SYSTEM_ORGANIZATION.CREATED
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ORGANIZATION.LASTMOD
     *
     * @return the value of SYSTEM_ORGANIZATION.LASTMOD
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    public Date getLastmod() {
        return lastmod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ORGANIZATION.LASTMOD
     *
     * @param lastmod the value for SYSTEM_ORGANIZATION.LASTMOD
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    public void setLastmod(Date lastmod) {
        this.lastmod = lastmod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ORGANIZATION.SHORT_NAME
     *
     * @return the value of SYSTEM_ORGANIZATION.SHORT_NAME
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ORGANIZATION.SHORT_NAME
     *
     * @param shortName the value for SYSTEM_ORGANIZATION.SHORT_NAME
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    public void setShortName(String shortName) {
        this.shortName = shortName == null ? null : shortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ORGANIZATION.TEL
     *
     * @return the value of SYSTEM_ORGANIZATION.TEL
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ORGANIZATION.TEL
     *
     * @param tel the value for SYSTEM_ORGANIZATION.TEL
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ORGANIZATION.FAX
     *
     * @return the value of SYSTEM_ORGANIZATION.FAX
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ORGANIZATION.FAX
     *
     * @param fax the value for SYSTEM_ORGANIZATION.FAX
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ORGANIZATION.DESCRIPTION
     *
     * @return the value of SYSTEM_ORGANIZATION.DESCRIPTION
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ORGANIZATION.DESCRIPTION
     *
     * @param description the value for SYSTEM_ORGANIZATION.DESCRIPTION
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ORGANIZATION.CREATER
     *
     * @return the value of SYSTEM_ORGANIZATION.CREATER
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    public Long getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ORGANIZATION.CREATER
     *
     * @param creater the value for SYSTEM_ORGANIZATION.CREATER
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    public void setCreater(Long creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_ORGANIZATION.MODIFYER
     *
     * @return the value of SYSTEM_ORGANIZATION.MODIFYER
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    public Long getModifyer() {
        return modifyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_ORGANIZATION.MODIFYER
     *
     * @param modifyer the value for SYSTEM_ORGANIZATION.MODIFYER
     *
     * @mbggenerated Mon Jun 26 09:58:35 CST 2017
     */
    public void setModifyer(Long modifyer) {
        this.modifyer = modifyer;
    }
}